/* Giá sản phẩm không được âm.*/
ALTER TABLE PRODUCT
ADD CONSTRAINT CK_PRODUCT_PRICE
CHECK (PRICE > 0);

/* Số lượng tồn kho không được âm. */
ALTER TABLE INVENTORY
ADD CONSTRAINT CK_INVENTORY_QUANTITY
CHECK (QUANTITY >= 0);

/* Phí vận chuyển phải >=0 */
ALTER TABLE ORDERS
ADD CONSTRAINT CK_ORDERS_SHIPPINGFEE
CHECK ( SHIPPING_FEE > = 0 );

/* số lượng và giá cả phải lớn hơn 0 */
ALTER TABLE ORDER_DETAIL
ADD CONSTRAINT CK_ORDER_DETAIL_QUANTITY
CHECK (QUANTITY > 0);

ALTER TABLE ORDER_DETAIL
ADD CONSTRAINT CK_ORDER_DETAIL_PRICE
CHECK (PRICE >= 0);

/* phần trăm giảm giá hợp lệ (group_buy) */
ALTER TABLE GROUP_BUY
ADD CONSTRAINT CK_GROUP_BUY_DISCOUNT
CHECK (DISCOUNT_PERCENT BETWEEN 0 AND 100);

  /*  CONSTRAINT CHK_GROUP_TIME
        CHECK (EXPIRY_TIME > START_AT)

      CONSTRAINT CHK_COUPON_TIME
        CHECK (END_AT > START_AT)

      CHECK (END_AT > START_AT), BẢNG PROMOTION
      */
