/* ================= ACCOUNT ================= */
ALTER TABLE ACCOUNT
ADD CONSTRAINT FK_ACCOUNT_USER
FOREIGN KEY (USER_ID)
REFERENCES USERS(USER_ID);

/* ================= ROLE ================= */
ALTER TABLE ROLE
ADD CONSTRAINT FK_ROLE_FUNCTION
FOREIGN KEY (FUNCTION_ID)
REFERENCES FUNCTIONS(FUNCTION_ID);

/* ================= ROLE_GROUP_ASSIGN_ROLE ================= */
ALTER TABLE ROLE_GROUP_ASSIGN_ROLE
ADD CONSTRAINT FK_RGR_ROLE_GROUP
FOREIGN KEY (ROLE_GROUP_ID)
REFERENCES ROLE_GROUP(ROLE_GROUP_ID);

ALTER TABLE ROLE_GROUP_ASSIGN_ROLE
ADD CONSTRAINT FK_RGR_ROLE
FOREIGN KEY (ROLE_ID)
REFERENCES ROLE(ROLE_ID);

/* ================= ACCOUNT_ASSIGN_ROLE_GROUP ================= */
ALTER TABLE ACCOUNT_ASSIGN_ROLE_GROUP
ADD CONSTRAINT FK_AARG_ACCOUNT
FOREIGN KEY (ACCOUNT_ID)
REFERENCES ACCOUNT(ACCOUNT_ID);

ALTER TABLE ACCOUNT_ASSIGN_ROLE_GROUP
ADD CONSTRAINT FK_AARG_ROLE_GROUP
FOREIGN KEY (ROLE_GROUP_ID)
REFERENCES ROLE_GROUP(ROLE_GROUP_ID);

/* ================= ACCOUNT_ASSIGN_ROLE ================= */
ALTER TABLE ACCOUNT_ASSIGN_ROLE
ADD CONSTRAINT FK_AAR_ACCOUNT
FOREIGN KEY (ACCOUNT_ID)
REFERENCES ACCOUNT(ACCOUNT_ID);

ALTER TABLE ACCOUNT_ASSIGN_ROLE
ADD CONSTRAINT FK_AAR_ROLE
FOREIGN KEY (ROLE_ID)
REFERENCES ROLE(ROLE_ID);

/* ================= CATEGORY ================= */
ALTER TABLE CATEGORY
ADD CONSTRAINT FK_CATEGORY_PARENT
FOREIGN KEY (PARENT_CATEGORY_ID)
REFERENCES CATEGORY(CATEGORY_ID);

/* ================= PRODUCT ================= */
ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_CATEGORY
FOREIGN KEY (CATEGORY_ID)
REFERENCES CATEGORY(CATEGORY_ID);

/* ================= INVENTORY ================= */
ALTER TABLE INVENTORY
ADD CONSTRAINT FK_INVENTORY_PRODUCT
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT(PRODUCT_ID);

ALTER TABLE INVENTORY
ADD CONSTRAINT FK_INVENTORY_WAREHOUSE
FOREIGN KEY (WAREHOUSE_ID)
REFERENCES WAREHOUSE(WAREHOUSE_ID);

/* ================= ORDERS ================= */
ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDER_CUSTOMER
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMER(CUSTOMER_ID);

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDER_COUPON
FOREIGN KEY (COUPON_ID)
REFERENCES COUPON(COUPON_ID);

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDER_WAREHOUSE
FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID);

/* ================= ORDER_DETAIL ================= */
ALTER TABLE ORDER_DETAIL
ADD CONSTRAINT FK_ORDER_DETAIL_ORDER
FOREIGN KEY (ORDER_ID)
REFERENCES ORDERS(ORDER_ID);

ALTER TABLE ORDER_DETAIL
ADD CONSTRAINT FK_ORDER_DETAIL_PRODUCT
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT(PRODUCT_ID);

/* ================= GROUP_BUY ================= */
ALTER TABLE GROUP_BUY
ADD CONSTRAINT FK_GROUPBUY_PRODUCT
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT(PRODUCT_ID);

/* ================= GROUP_MEMBER ================= */
ALTER TABLE GROUP_MEMBER
ADD CONSTRAINT FK_GROUP_MEMBER_GROUP
FOREIGN KEY (GROUP_ID)
REFERENCES GROUP_BUY(GROUP_ID);

ALTER TABLE GROUP_MEMBER
ADD CONSTRAINT FK_GROUP_MEMBER_USER
FOREIGN KEY (USER_ID)
REFERENCES USERS(USER_ID);

ALTER TABLE GROUP_MEMBER
ADD CONSTRAINT FK_GROUP_MEMBER_ORDER
FOREIGN KEY (ORDER_ID)
REFERENCES ORDERS(ORDER_ID);

/* ================= REVIEW ================= */
ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_CUSTOMER
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMER(CUSTOMER_ID);

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_PRODUCT
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT(PRODUCT_ID);

/* ================= PAYMENT ================= */
ALTER TABLE PAYMENT
ADD CONSTRAINT FK_PAYMENT_ORDER
FOREIGN KEY (ORDER_ID)
REFERENCES ORDERS(ORDER_ID);

/* ================= COUPON ================= */
ALTER TABLE COUPON
ADD CONSTRAINT FK_COUPON_AFFILIATE
FOREIGN KEY (AFFILIATE_ID)
REFERENCES AFFILIATE(AFFILIATE_ID);

/* ================= PROMOTION_PRODUCT ================= */
ALTER TABLE PROMOTION_PRODUCT
ADD CONSTRAINT FK_PROMOTION_PRODUCT_PROMOTION
FOREIGN KEY (PROMOTION_ID)
REFERENCES PROMOTION(PROMOTION_ID);

ALTER TABLE PROMOTION_PRODUCT
ADD CONSTRAINT FK_PROMOTION_PRODUCT_PRODUCT
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT(PRODUCT_ID);

/* ================= WARRANTY ================= */
ALTER TABLE WARRANTY
ADD CONSTRAINT FK_WARRANTY_PRODUCT
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT(PRODUCT_ID);

ALTER TABLE WARRANTY
ADD CONSTRAINT FK_WARRANTY_ORDER_DETAIL
FOREIGN KEY (ORDER_DETAIL_ID)
REFERENCES ORDER_DETAIL(ORDER_DETAIL_ID);

/* ================= CART ================= */
ALTER TABLE CART
ADD CONSTRAINT FK_CART_USER
FOREIGN KEY (USER_ID)
REFERENCES USERS(USER_ID);

/* ================= CART_ITEM ================= */
ALTER TABLE CART_ITEM
ADD CONSTRAINT FK_CART_ITEM_CART
FOREIGN KEY (CART_ID)
REFERENCES CART(CART_ID);

ALTER TABLE CART_ITEM
ADD CONSTRAINT FK_CART_ITEM_PRODUCT
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT(PRODUCT_ID);


/* ================= LOYALTY_POINT ================= */
ALTER TABLE LOYALTY_POINT
ADD CONSTRAINT FK_LOYALTY_POINT_CUSTOMER
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMER(CUSTOMER_ID);