-- 1. Quản lý giỏ hàng duy nhất
CREATE OR REPLACE TRIGGER TRG_LIMIT_ONE_ACTIVE_CART
BEFORE INSERT ON CART FOR EACH ROW
BEGIN
    IF :NEW.STATUS = 'ACTIVE' THEN
        UPDATE CART SET STATUS = 'CANCELLED'
        WHERE USER_ID = :NEW.USER_ID AND STATUS = 'ACTIVE';
    END IF;
END;
/

-- 2. Tự động tính tổng tiền đơn hàng
CREATE OR REPLACE TRIGGER TRG_ORDER_TOTAL_CALC
AFTER INSERT OR UPDATE OR DELETE ON ORDER_DETAIL
FOR EACH ROW
BEGIN
    IF INSERTING OR UPDATING THEN
        UPDATE ORDERS SET TOTAL_AMOUNT = (SELECT SUM(PRICE * QUANTITY) FROM ORDER_DETAIL WHERE ORDER_ID = :NEW.ORDER_ID)
        WHERE ORDER_ID = :NEW.ORDER_ID;
    ELSIF DELETING THEN
        UPDATE ORDERS SET TOTAL_AMOUNT = (SELECT SUM(PRICE * QUANTITY) FROM ORDER_DETAIL WHERE ORDER_ID = :OLD.ORDER_ID)
        WHERE ORDER_ID = :OLD.ORDER_ID;
    END IF;
END;
/

-- 3. Khấu trừ tồn kho khi đặt hàng
CREATE OR REPLACE TRIGGER TRG_DEDUCT_INVENTORY
AFTER INSERT ON ORDER_DETAIL FOR EACH ROW
BEGIN
    UPDATE INVENTORY SET QUANTITY = QUANTITY - :NEW.QUANTITY
    WHERE PRODUCT_ID = :NEW.PRODUCT_ID;
END;
/

-- 4. Ngăn chặn xuất kho âm
CREATE OR REPLACE TRIGGER TRG_PREVENT_NEGATIVE_STOCK
BEFORE UPDATE ON INVENTORY FOR EACH ROW
BEGIN
    IF :NEW.QUANTITY < 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Lỗi: Số lượng tồn kho không đủ để xuất hàng!');
    END IF;
END;
/

-- 5. Hoàn kho khi hủy đơn hàng
CREATE OR REPLACE TRIGGER TRG_RESTORE_INVENTORY
AFTER UPDATE OF STATUS ON ORDERS FOR EACH ROW
WHEN (NEW.STATUS = 'CANCELLED')
BEGIN
    FOR r IN (SELECT PRODUCT_ID, QUANTITY FROM ORDER_DETAIL WHERE ORDER_ID = :NEW.ORDER_ID) LOOP
        UPDATE INVENTORY SET QUANTITY = QUANTITY + r.QUANTITY
        WHERE PRODUCT_ID = r.PRODUCT_ID;
    END LOOP;
END;
/

-- 6. Đồng bộ trạng thái Thanh toán - Đơn hàng
CREATE OR REPLACE TRIGGER TRG_PAYMENT_ORDER_SYNC
AFTER UPDATE OF STATUS ON PAYMENT FOR EACH ROW
WHEN (NEW.STATUS = 'SUCCESS')
BEGIN
    UPDATE ORDERS SET STATUS = 'PROCESSING' WHERE ORDER_ID = :NEW.ORDER_ID;
END;
/

-- 7. Tích điểm khách hàng
CREATE OR REPLACE TRIGGER TRG_LOYALTY_POINTS_ADD
AFTER UPDATE OF STATUS ON ORDERS FOR EACH ROW
WHEN (NEW.STATUS = 'COMPLETED')
BEGIN
    UPDATE LOYALTY_POINT SET TOTAL_POINTS = TOTAL_POINTS + (:NEW.TOTAL_AMOUNT * 0.01)
    WHERE CUSTOMER_ID = :NEW.CUSTOMER_ID;
END;
/

-- 8. Quản lý số lần dùng Coupon
CREATE OR REPLACE TRIGGER TRG_COUPON_USAGE_COUNT
AFTER INSERT ON ORDERS FOR EACH ROW
WHEN (NEW.COUPON_ID IS NOT NULL)
BEGIN
    UPDATE COUPON SET USED_COUNT = USED_COUNT + 1 WHERE COUPON_ID = :NEW.COUPON_ID;
END;
/

-- 9. Kiểm tra điều kiện đơn tối thiểu (Mã giảm giá)
CREATE OR REPLACE TRIGGER TRG_VALIDATE_COUPON_MIN_ORDER
BEFORE INSERT OR UPDATE ON ORDERS FOR EACH ROW
DECLARE
    v_min_val NUMBER;
BEGIN
    IF :NEW.COUPON_ID IS NOT NULL THEN
        SELECT MIN_ORDER_VALUE INTO v_min_val FROM COUPON WHERE COUPON_ID = :NEW.COUPON_ID;
        IF :NEW.TOTAL_AMOUNT < v_min_val THEN
            RAISE_APPLICATION_ERROR(-20005, 'Đơn hàng không đạt giá trị tối thiểu để dùng mã này.');
        END IF;
    END IF;
END;
/

-- 10. Kích hoạt bảo hành tự động
CREATE OR REPLACE TRIGGER TRG_WARRANTY_AUTO_GEN
AFTER UPDATE OF STATUS ON ORDERS FOR EACH ROW
WHEN (NEW.STATUS = 'DELIVERED')
BEGIN
    FOR r IN (SELECT PRODUCT_ID FROM ORDER_DETAIL WHERE ORDER_ID = :NEW.ORDER_ID) LOOP
        INSERT INTO WARRANTY (ORDER_ID, PRODUCT_ID, START_AT, END_AT, STATUS)
        VALUES (:NEW.ORDER_ID, r.PRODUCT_ID, SYSDATE, SYSDATE + 365, 'ACTIVE');
    END LOOP;
END;
/

-- 11. Chặn đánh giá ảo (Phải mua mới được đánh giá)
CREATE OR REPLACE TRIGGER TRG_REVIEW_VALIDATE_PURCHASE
BEFORE INSERT ON REVIEW FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM ORDERS o
    JOIN ORDER_DETAIL od ON o.ORDER_ID = od.ORDER_ID
    WHERE o.CUSTOMER_ID = :NEW.CUSTOMER_ID AND od.PRODUCT_ID = :NEW.PRODUCT_ID AND o.STATUS = 'DELIVERED';

    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20010, 'Bạn cần mua sản phẩm này trước khi để lại đánh giá.');
    END IF;
END;
/

-- 12. Cập nhật điểm tín nhiệm sản phẩm
CREATE OR REPLACE TRIGGER TRG_UPDATE_PRODUCT_RATING
AFTER INSERT OR UPDATE ON REVIEW FOR EACH ROW
BEGIN
    UPDATE PRODUCT SET RATING = (SELECT AVG(RATING) FROM REVIEW WHERE PRODUCT_ID = :NEW.PRODUCT_ID)
    WHERE PRODUCT_ID = :NEW.PRODUCT_ID;
END;
/

-- 13. Tự động hóa mua chung
CREATE OR REPLACE TRIGGER TRG_GROUP_BUY_SUCCESS_CHECK
AFTER INSERT ON GROUP_MEMBER FOR EACH ROW
DECLARE
    v_current NUMBER; v_max NUMBER;
BEGIN
    SELECT CURRENT_MEMBERS, MAX_MEMBERS INTO v_current, v_max FROM GROUP_BUY WHERE GROUP_ID = :NEW.GROUP_ID;
    IF v_current >= v_max THEN
        UPDATE GROUP_BUY SET STATUS = 'SUCCESS' WHERE GROUP_ID = :NEW.GROUP_ID;
    END IF;
END;
/

-- 14. Kiểm tra hạn khuyến mãi
CREATE OR REPLACE TRIGGER TRG_PROMOTION_DATE_VALIDATE
BEFORE INSERT ON PROMOTION_PRODUCT FOR EACH ROW
DECLARE
    v_end DATE;
BEGIN
    SELECT END_AT INTO v_end FROM PROMOTION WHERE PROMOTION_ID = :NEW.PROMOTION_ID;
    IF v_end < SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20015, 'Chương trình khuyến mãi này đã kết thúc.');
    END IF;
END;
/

-- 15. Tính hoa hồng giới thiệu (Affiliate)
CREATE OR REPLACE TRIGGER TRG_AFFILIATE_COMMISSION
AFTER UPDATE OF STATUS ON ORDERS FOR EACH ROW
WHEN (NEW.STATUS = 'COMPLETED' AND NEW.AFFILIATE_ID IS NOT NULL)
BEGIN
    UPDATE AFFILIATE SET TOTAL_EARNED = TOTAL_EARNED + (:NEW.TOTAL_AMOUNT * 0.05)
    WHERE AFFILIATE_ID = :NEW.AFFILIATE_ID;
END;
/

-- 16. Kiểm tra tính đúng đắn số tiền thanh toán
CREATE OR REPLACE TRIGGER TRG_VALIDATE_PAYMENT_AMOUNT
BEFORE INSERT ON PAYMENT FOR EACH ROW
DECLARE
    v_total NUMBER;
BEGIN
    SELECT TOTAL_AMOUNT INTO v_total FROM ORDERS WHERE ORDER_ID = :NEW.ORDER_ID;
    IF :NEW.AMOUNT != v_total THEN
        RAISE_APPLICATION_ERROR(-20020, 'Số tiền thanh toán không khớp với đơn hàng.');
    END IF;
END;
/

-- 17. [MỚI] Ngăn chặn dùng mã giảm giá khi đã hết lượt
CREATE OR REPLACE TRIGGER TRG_COUPON_MAX_USAGE_CHECK
BEFORE INSERT OR UPDATE ON ORDERS FOR EACH ROW
DECLARE
    v_used NUMBER;
    v_max NUMBER;
BEGIN
    IF :NEW.COUPON_ID IS NOT NULL THEN
        SELECT USED_COUNT, MAX_USAGE INTO v_used, v_max FROM COUPON WHERE COUPON_ID = :NEW.COUPON_ID;
        IF v_used >= v_max THEN
            RAISE_APPLICATION_ERROR(-20030, 'Mã giảm giá này đã hết lượt sử dụng.');
        END IF;
    END IF;
END;
/

-- 18. Kiểm tra mã số thuế khách hàng (VAT)
CREATE OR REPLACE TRIGGER TRG_CHECK_CUSTOMER_VAT
BEFORE INSERT OR UPDATE ON CUSTOMER FOR EACH ROW
BEGIN
    IF :NEW.VAT_CODE IS NOT NULL AND LENGTH(:NEW.VAT_CODE) != 10 THEN
        RAISE_APPLICATION_ERROR(-20025, 'Mã số thuế phải có đúng 10 chữ số.');
    END IF;
END;
/

-- 19. [MỚI] Ngăn chặn hủy đơn hàng khi đã được giao đi
CREATE OR REPLACE TRIGGER TRG_PREVENT_CANCEL_SHIPPED_ORDER
BEFORE UPDATE OF STATUS ON ORDERS FOR EACH ROW
BEGIN
    IF :NEW.STATUS = 'CANCELLED' AND :OLD.STATUS IN ('SHIPPED', 'DELIVERED') THEN
        RAISE_APPLICATION_ERROR(-20032, 'Không thể hủy đơn hàng đã xuất kho hoặc đã giao thành công.');
    END IF;
END;
/

-- 20. [MỚI] Chặn nhập sai mức giảm giá (Chống xả kho lộn giá)
CREATE OR REPLACE TRIGGER TRG_CHECK_DISCOUNT_LIMIT
BEFORE INSERT OR UPDATE ON PROMOTION FOR EACH ROW
BEGIN
    IF :NEW.DISCOUNT_TYPE = 'PERCENTAGE' AND :NEW.DISCOUNT_VALUE > 100 THEN
        RAISE_APPLICATION_ERROR(-20033, 'Lỗi: Mức giảm giá theo phần trăm không được vượt quá 100%.');
    END IF;
END;
/