/* AUTO TIMESTAMP TRIGGERS */

/* USERS */
CREATE OR REPLACE TRIGGER TRG_USERS_AUDIT
BEFORE INSERT OR UPDATE ON USERS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_AT := SYSDATE;
    END IF;
    :NEW.UPDATED_AT := SYSDATE;
END;


/* ACCOUNT */
CREATE OR REPLACE TRIGGER TRG_ACCOUNT_AUDIT
BEFORE INSERT OR UPDATE ON ACCOUNT
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_AT := SYSDATE;
    END IF;
    :NEW.UPDATED_AT := SYSDATE;
END;


/* PRODUCT */
CREATE OR REPLACE TRIGGER TRG_PRODUCT_AUDIT
BEFORE INSERT OR UPDATE ON PRODUCT
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_AT := SYSDATE;
    END IF;
    :NEW.UPDATED_AT := SYSDATE;
END;


/* CUSTOMER */
CREATE OR REPLACE TRIGGER TRG_CUSTOMER_AUDIT
BEFORE INSERT OR UPDATE ON CUSTOMER
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_AT := SYSDATE;
    END IF;
    :NEW.UPDATED_AT := SYSDATE;
END;


/* INVENTORY */
CREATE OR REPLACE TRIGGER TRG_INVENTORY_AUDIT
BEFORE INSERT OR UPDATE ON INVENTORY
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_AT := SYSDATE;
    END IF;
    :NEW.UPDATED_AT := SYSDATE;
END;


/* PAYMENT */
CREATE OR REPLACE TRIGGER TRG_PAYMENT_AUDIT
BEFORE INSERT OR UPDATE ON PAYMENT
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_AT := SYSDATE;
    END IF;
    :NEW.UPDATED_AT := SYSDATE;
END;


/* COUPON */
CREATE OR REPLACE TRIGGER TRG_COUPON_AUDIT
BEFORE INSERT OR UPDATE ON COUPON
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_AT := SYSDATE;
    END IF;
    :NEW.UPDATED_AT := SYSDATE;
END;


/* WARRANTY */
CREATE OR REPLACE TRIGGER TRG_WARRANTY_AUDIT
BEFORE INSERT OR UPDATE ON WARRANTY
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREATED_AT := SYSDATE;
    END IF;
    :NEW.UPDATED_AT := SYSDATE;
END;

/* AUTO UPDATE INVENTORY WHEN ORDER CREATED */

CREATE OR REPLACE TRIGGER TRG_ORDER_DEDUCT_STOCK
AFTER INSERT ON ORDER_DETAIL
FOR EACH ROW
BEGIN
    UPDATE INVENTORY
    SET QUANTITY = QUANTITY - :NEW.QUANTITY,
        UPDATED_AT = SYSDATE
    WHERE PRODUCT_ID = :NEW.PRODUCT_ID;
END;


/* AUTO ADD LOYALTY POINT */

CREATE OR REPLACE TRIGGER TRG_ADD_LOYALTY_POINT
AFTER UPDATE OF STATUS ON ORDERS
FOR EACH ROW
WHEN (NEW.STATUS = 'DELIVERED')
BEGIN
    UPDATE LOYALTY_POINT
    SET TOTAL_POINTS = TOTAL_POINTS + FLOOR(:NEW.TOTAL / 1000),
        UPDATED_AT = SYSDATE
    WHERE CUSTOMER_ID = :NEW.CUSTOMER_ID;
END;

/* AUTO UPDATE GROUP BUY PARTICIPANTS */

CREATE OR REPLACE TRIGGER TRG_GROUP_MEMBER_COUNT
AFTER INSERT ON GROUP_MEMBER
FOR EACH ROW
BEGIN
    UPDATE GROUP_BUY
    SET CUR_PARTICIPANTS = CUR_PARTICIPANTS + 1,
        UPDATED_AT = SYSDATE
    WHERE GROUP_ID = :NEW.GROUP_ID;
END;


