/**
  AUDIT TRIGGER
 */

/* PRODUCT updated_at */
CREATE OR REPLACE TRIGGER TRG_PRODUCT_UPDATED
BEFORE UPDATE ON PRODUCT
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSDATE;
END;

/* CUSTOMER updated_at */
CREATE OR REPLACE TRIGGER TRG_CUSTOMER_UPDATED
BEFORE UPDATE ON CUSTOMER
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSDATE;
END;

/*  ACCOUNT updated_at */
CREATE OR REPLACE TRIGGER TRG_ACCOUNT_UPDATED
BEFORE UPDATE ON ACCOUNT
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSDATE;
END;
/
/* CART updated_at */
CREATE OR REPLACE TRIGGER TRG_CART_UPDATED
BEFORE UPDATE ON CART
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSDATE;
END;

/**
Bảng có thể áp dụng thêm
ROLE
ROLE_GROUP
GROUP_BUY
AFFILIATE
CATEGORY
 */

/**
  VALIDATION TRIGGER (XÀI CHECK)
 */

/* Check inventory before order */
CREATE OR REPLACE TRIGGER TRG_CHECK_INVENTORY
BEFORE INSERT ON ORDER_DETAIL
FOR EACH ROW
DECLARE
    V_STOCK NUMBER;
BEGIN

    SELECT QUANTITY
    INTO V_STOCK
    FROM INVENTORY
    WHERE PRODUCT_ID = :NEW.PRODUCT_ID;

    IF V_STOCK < :NEW.QUANTITY THEN
        RAISE_APPLICATION_ERROR(-20007,'Not enough stock');
    END IF;

END;

/* Check group buy expiry */
CREATE OR REPLACE TRIGGER TRG_GROUP_MEMBER_VALIDATE
BEFORE INSERT ON GROUP_MEMBER
FOR EACH ROW
DECLARE
    V_EXP DATE;
BEGIN

    SELECT EXPIRY_TIME
    INTO V_EXP
    FROM GROUP_BUY
    WHERE GROUP_ID = :NEW.GROUP_ID;

    IF V_EXP < SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20008,'Group buy expired');
    END IF;

END;

/* Prevent duplicate review */
CREATE OR REPLACE TRIGGER TRG_REVIEW_DUPLICATE
BEFORE INSERT ON REVIEW
FOR EACH ROW
DECLARE
    V_COUNT NUMBER;
BEGIN

    SELECT COUNT(*)
    INTO V_COUNT
    FROM REVIEW
    WHERE CUSTOMER_ID = :NEW.CUSTOMER_ID
    AND PRODUCT_ID = :NEW.PRODUCT_ID;

    IF V_COUNT > 0 THEN
        RAISE_APPLICATION_ERROR(-20009,'Already reviewed');
    END IF;

END;

/* Validate coupon minimum order */
CREATE OR REPLACE TRIGGER TRG_COUPON_MIN_ORDER
BEFORE UPDATE ON ORDERS
FOR EACH ROW
DECLARE
    V_MIN NUMBER;
BEGIN

    IF :NEW.COUPON_ID IS NOT NULL THEN

        SELECT MIN_ORDER_VALUE
        INTO V_MIN
        FROM COUPON
        WHERE COUPON_ID = :NEW.COUPON_ID;

        IF :NEW.TOTAL < V_MIN THEN
            RAISE_APPLICATION_ERROR(-20010,'Order not eligible for coupon');
        END IF;

    END IF;

END;

/* Check shipment after order */
CREATE OR REPLACE TRIGGER TRG_SHIPMENT_VALIDATE
BEFORE INSERT ON SHIPMENT
FOR EACH ROW
DECLARE
    V_COUNT NUMBER;
BEGIN

    SELECT COUNT(*)
    INTO V_COUNT
    FROM ORDERS
    WHERE ORDER_ID = :NEW.ORDER_ID;

    IF V_COUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20011,'Order not found');
    END IF;

END;

/* AUTOMATION TRIGGER (5 trigger) */


/* Auto calculate order total */
CREATE OR REPLACE TRIGGER TRG_ORDER_TOTAL
AFTER INSERT OR UPDATE OR DELETE ON ORDER_DETAIL
FOR EACH ROW
DECLARE
    V_TOTAL NUMBER;
    V_ORDER NUMBER;
BEGIN

    IF INSERTING OR UPDATING THEN
        V_ORDER := :NEW.ORDER_ID;
    ELSE
        V_ORDER := :OLD.ORDER_ID;
    END IF;

    SELECT NVL(SUM(PRICE * QUANTITY),0)
    INTO V_TOTAL
    FROM ORDER_DETAIL
    WHERE ORDER_ID = V_ORDER;

    UPDATE ORDERS
    SET TOTAL = V_TOTAL
    WHERE ORDER_ID = V_ORDER;

END;

/* Auto apply promotion */
CREATE OR REPLACE TRIGGER TRG_PROMOTION_APPLY
BEFORE INSERT ON ORDER_DETAIL
FOR EACH ROW
DECLARE
    V_DISCOUNT NUMBER;
BEGIN

    SELECT DISCOUNT_VALUE
    INTO V_DISCOUNT
    FROM PROMOTION_PRODUCT
    WHERE PRODUCT_ID = :NEW.PRODUCT_ID
    AND ROWNUM = 1;

    :NEW.PRICE := :NEW.PRICE - V_DISCOUNT;

EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;

END;

/* Deduct inventory after payment */
CREATE OR REPLACE TRIGGER TRG_ORDER_DEDUCT_INVENTORY
AFTER UPDATE OF STATUS ON ORDERS
FOR EACH ROW
WHEN (NEW.STATUS = 'CONFIRMED')
BEGIN

    UPDATE INVENTORY I
    SET I.QUANTITY = I.QUANTITY - (
        SELECT OD.QUANTITY
        FROM ORDER_DETAIL OD
        WHERE OD.ORDER_ID = :NEW.ORDER_ID
        AND OD.PRODUCT_ID = I.PRODUCT_ID
    )
    WHERE I.PRODUCT_ID IN
    (
        SELECT PRODUCT_ID
        FROM ORDER_DETAIL
        WHERE ORDER_ID = :NEW.ORDER_ID
    );

END;

/* Auto update affiliate commission */
CREATE OR REPLACE TRIGGER TRG_AFFILIATE_COMMISSION
AFTER UPDATE OF PAYMENT_STATUS ON PAYMENT
FOR EACH ROW
WHEN (NEW.PAYMENT_STATUS = 'PAID')
BEGIN

    UPDATE AFFILIATE
    SET TOTAL_EARNED = TOTAL_EARNED + (:NEW.AMOUNT * COMMISSION_RATE / 100);

END;

/* Auto close group buy */
CREATE OR REPLACE TRIGGER TRG_GROUP_BUY_CLOSE
AFTER UPDATE ON GROUP_BUY
FOR EACH ROW
BEGIN

    IF :NEW.EXPIRY_TIME < SYSDATE THEN
        :NEW.STATUS := 'CLOSED';
    END IF;

END;
