/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.panel.admin;

import Util.TableDecorate;
import Controller.adminPageController;
import View.admin.AdminForm;
import View.dialog.dialogThemQuyen;

/**
 *
 * @author phamd
 */
public class panelTaikhoan extends javax.swing.JPanel {

    private adminPageController adminController = new adminPageController();
    private TableDecorate tableAction = new TableDecorate();

    /**
     * Creates new form panelTaikhoan
     */
    public panelTaikhoan() {
        initComponents();

        //Admin account
        adminController.setUpTable(tblAdminAccount, 6);
        adminController.loadDataToTableAdminAccount(tblAdminAccount);

        //Customer account
        adminController.setUpTable(tblCustomerAccount, 5);
        adminController.loadDataToTableCustomerAccount(tblCustomerAccount);

        //Decorate Table
        TableDecorate.StatusRenderer statusRenderer = new TableDecorate().new StatusRenderer();
        tblAdminAccount.getColumnModel().getColumn(6).setCellRenderer(statusRenderer); //cho cột trạng thái đẹp hơn
        tblCustomerAccount.getColumnModel().getColumn(5).setCellRenderer(statusRenderer); //cho cột trạng thái đẹp hơn
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlAdminAccount = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdminAccount = new javax.swing.JTable();
        txtFindAccount = new Custom_Component.MyTextField();
        imagePanel1 = new Custom_Component.ImagePanel();
        btnDeleteAcc = new Custom_Component.MyButton();
        btnAddAcc = new Custom_Component.MyButton();
        btnEditAcc = new Custom_Component.MyButton();
        pnlCustomerAccount = new javax.swing.JPanel();
        pnlcus = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCustomerAccount = new javax.swing.JTable();
        txtFindCusAccount = new Custom_Component.MyTextField();
        imagePanel2 = new Custom_Component.ImagePanel();
        btnDeleteCusAcc = new Custom_Component.MyButton();
        btnAddCusAcc = new Custom_Component.MyButton();
        btnEditCusAcc = new Custom_Component.MyButton();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("QUẢN LÝ TÀI KHOẢN");

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        pnlAdminAccount.setBackground(new java.awt.Color(255, 255, 255));
        pnlAdminAccount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Danh Sách Tài Khoản Admin & Nhân Viên Trong Hệ Thống");

        tblAdminAccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblAdminAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên đăng nhập", "AccountID", "Họ và tên", "SĐT", "Địa chỉ", "Vai trò", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAdminAccount.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tblAdminAccount);
        if (tblAdminAccount.getColumnModel().getColumnCount() > 0) {
            tblAdminAccount.getColumnModel().getColumn(1).setMinWidth(0);
            tblAdminAccount.getColumnModel().getColumn(1).setPreferredWidth(0);
            tblAdminAccount.getColumnModel().getColumn(1).setMaxWidth(0);
            tblAdminAccount.getColumnModel().getColumn(5).setHeaderValue("Vai trò");
        }

        imagePanel1.setImage(new javax.swing.ImageIcon(getClass().getResource("/Resource/search.png"))); // NOI18N

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnDeleteAcc.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleteAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteAcc.setText("Xóa tài khoản");
        btnDeleteAcc.setColorClick(new java.awt.Color(0, 0, 255));
        btnDeleteAcc.setColorHover(new java.awt.Color(51, 102, 255));
        btnDeleteAcc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteAcc.addActionListener(this::btnDeleteAccActionPerformed);

        btnAddAcc.setBackground(new java.awt.Color(51, 51, 255));
        btnAddAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnAddAcc.setText("Thêm tài khoản");
        btnAddAcc.setColorClick(new java.awt.Color(0, 0, 255));
        btnAddAcc.setColorHover(new java.awt.Color(51, 102, 255));
        btnAddAcc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddAcc.addActionListener(this::btnAddAccActionPerformed);

        btnEditAcc.setBackground(new java.awt.Color(51, 51, 255));
        btnEditAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnEditAcc.setText("Sửa tài khoản");
        btnEditAcc.setColorClick(new java.awt.Color(0, 0, 255));
        btnEditAcc.setColorHover(new java.awt.Color(51, 102, 255));
        btnEditAcc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditAcc.addActionListener(this::btnEditAccActionPerformed);

        javax.swing.GroupLayout pnlAdminAccountLayout = new javax.swing.GroupLayout(pnlAdminAccount);
        pnlAdminAccount.setLayout(pnlAdminAccountLayout);
        pnlAdminAccountLayout.setHorizontalGroup(
            pnlAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminAccountLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(imagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFindAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminAccountLayout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addComponent(btnAddAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(pnlAdminAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAdminAccountLayout.setVerticalGroup(
            pnlAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFindAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jTabbedPane1.addTab("Tài khoản Admin & Nhân viên", pnlAdminAccount);

        pnlcus.setBackground(new java.awt.Color(255, 255, 255));
        pnlcus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Danh Sách Tài Khoản Khách Hàng Trong Hệ Thống");

        tblCustomerAccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblCustomerAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tên đăng nhập", "AccountID", "Họ và tên", "SĐT", "Địa chỉ", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCustomerAccount.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(tblCustomerAccount);
        if (tblCustomerAccount.getColumnModel().getColumnCount() > 0) {
            tblCustomerAccount.getColumnModel().getColumn(1).setMinWidth(0);
            tblCustomerAccount.getColumnModel().getColumn(1).setPreferredWidth(0);
            tblCustomerAccount.getColumnModel().getColumn(1).setMaxWidth(0);
        }

        imagePanel2.setImage(new javax.swing.ImageIcon(getClass().getResource("/Resource/search.png"))); // NOI18N

        javax.swing.GroupLayout imagePanel2Layout = new javax.swing.GroupLayout(imagePanel2);
        imagePanel2.setLayout(imagePanel2Layout);
        imagePanel2Layout.setHorizontalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        imagePanel2Layout.setVerticalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnDeleteCusAcc.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleteCusAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteCusAcc.setText("Xóa tài khoản");
        btnDeleteCusAcc.setColorClick(new java.awt.Color(0, 0, 255));
        btnDeleteCusAcc.setColorHover(new java.awt.Color(51, 102, 255));
        btnDeleteCusAcc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteCusAcc.addActionListener(this::btnDeleteCusAccActionPerformed);

        btnAddCusAcc.setBackground(new java.awt.Color(51, 51, 255));
        btnAddCusAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCusAcc.setText("Thêm tài khoản");
        btnAddCusAcc.setColorClick(new java.awt.Color(0, 0, 255));
        btnAddCusAcc.setColorHover(new java.awt.Color(51, 102, 255));
        btnAddCusAcc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddCusAcc.addActionListener(this::btnAddCusAccActionPerformed);

        btnEditCusAcc.setBackground(new java.awt.Color(51, 51, 255));
        btnEditCusAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCusAcc.setText("Sửa tài khoản");
        btnEditCusAcc.setColorClick(new java.awt.Color(0, 0, 255));
        btnEditCusAcc.setColorHover(new java.awt.Color(51, 102, 255));
        btnEditCusAcc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditCusAcc.addActionListener(this::btnEditCusAccActionPerformed);

        javax.swing.GroupLayout pnlcusLayout = new javax.swing.GroupLayout(pnlcus);
        pnlcus.setLayout(pnlcusLayout);
        pnlcusLayout.setHorizontalGroup(
            pnlcusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlcusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlcusLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(imagePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFindCusAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(51, 51, 51))
                    .addGroup(pnlcusLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(129, Short.MAX_VALUE))))
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddCusAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditCusAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteCusAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        pnlcusLayout.setVerticalGroup(
            pnlcusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlcusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFindCusAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlcusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCusAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCusAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCusAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout pnlCustomerAccountLayout = new javax.swing.GroupLayout(pnlCustomerAccount);
        pnlCustomerAccount.setLayout(pnlCustomerAccountLayout);
        pnlCustomerAccountLayout.setHorizontalGroup(
            pnlCustomerAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
            .addGroup(pnlCustomerAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCustomerAccountLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlcus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        pnlCustomerAccountLayout.setVerticalGroup(
            pnlCustomerAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
            .addGroup(pnlCustomerAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCustomerAccountLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlcus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        jTabbedPane1.addTab("Tài khoản khách hàng", pnlCustomerAccount);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAccActionPerformed

    }//GEN-LAST:event_btnDeleteAccActionPerformed

    private void btnAddAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddAccActionPerformed

    private void btnEditAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditAccActionPerformed

    private void btnDeleteCusAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCusAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteCusAccActionPerformed

    private void btnAddCusAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCusAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCusAccActionPerformed

    private void btnEditCusAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCusAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditCusAccActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom_Component.MyButton btnAddAcc;
    private Custom_Component.MyButton btnAddCusAcc;
    private Custom_Component.MyButton btnDeleteAcc;
    private Custom_Component.MyButton btnDeleteCusAcc;
    private Custom_Component.MyButton btnEditAcc;
    private Custom_Component.MyButton btnEditCusAcc;
    private Custom_Component.ImagePanel imagePanel1;
    private Custom_Component.ImagePanel imagePanel2;
    private Custom_Component.ImagePanel imagePanel3;
    private Custom_Component.ImagePanel imagePanel4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JPanel pnlAdminAccount;
    private javax.swing.JPanel pnlAdminAccount2;
    private javax.swing.JPanel pnlAdminAccount3;
    private javax.swing.JPanel pnlContent2;
    private javax.swing.JPanel pnlContent3;
    private javax.swing.JPanel pnlCustomerAccount;
    private javax.swing.JPanel pnlcus;
    private javax.swing.JTable tblAdminAccount;
    private javax.swing.JTable tblAdminAccount2;
    private javax.swing.JTable tblAdminAccount3;
    private javax.swing.JTable tblCustomerAccount;
    private Custom_Component.MyTextField txtFindAccount;
    private Custom_Component.MyTextField txtFindAccount2;
    private Custom_Component.MyTextField txtFindAccount3;
    private Custom_Component.MyTextField txtFindCusAccount;
    // End of variables declaration//GEN-END:variables
}
