/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.panel.admin;

/**
 *
 * @author phamd
 */
public class panelKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form panelDanhmuc
     */
    public panelKhachHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCustomerAccount = new javax.swing.JPanel();
        pnlcus = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCustomerAccount = new javax.swing.JTable();
        txtFindCusAccount = new Custom_Component.MyTextField();
        imagePanel2 = new Custom_Component.ImagePanel();
        btnDeleteCusAcc = new Custom_Component.MyButton();
        btnAddCusAcc = new Custom_Component.MyButton();
        btnEditCusAcc = new Custom_Component.MyButton();

        pnlcus.setBackground(new java.awt.Color(255, 255, 255));
        pnlcus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Danh Sách Tài Khoản Khách Hàng Trong Hệ Thống");

        tblCustomerAccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblCustomerAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên đăng nhập", "AccountID", "Họ và tên", "SĐT", "Địa chỉ", "Ngày sinh", "Giới tính", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCustomerAccount.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(tblCustomerAccount);

        imagePanel2.setImage(new javax.swing.ImageIcon(getClass().getResource("/Resource/search.png"))); // NOI18N

        javax.swing.GroupLayout imagePanel2Layout = new javax.swing.GroupLayout(imagePanel2);
        imagePanel2.setLayout(imagePanel2Layout);
        imagePanel2Layout.setHorizontalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        imagePanel2Layout.setVerticalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnDeleteCusAcc.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleteCusAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteCusAcc.setText("Xóa tài khoản");
        btnDeleteCusAcc.setColorClick(new java.awt.Color(0, 0, 255));
        btnDeleteCusAcc.setColorHover(new java.awt.Color(51, 102, 255));
        btnDeleteCusAcc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteCusAcc.addActionListener(this::btnDeleteCusAccActionPerformed);

        btnAddCusAcc.setBackground(new java.awt.Color(51, 51, 255));
        btnAddCusAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCusAcc.setText("Thêm tài khoản");
        btnAddCusAcc.setColorClick(new java.awt.Color(0, 0, 255));
        btnAddCusAcc.setColorHover(new java.awt.Color(51, 102, 255));
        btnAddCusAcc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddCusAcc.addActionListener(this::btnAddCusAccActionPerformed);

        btnEditCusAcc.setBackground(new java.awt.Color(51, 51, 255));
        btnEditCusAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCusAcc.setText("Sửa tài khoản");
        btnEditCusAcc.setColorClick(new java.awt.Color(0, 0, 255));
        btnEditCusAcc.setColorHover(new java.awt.Color(51, 102, 255));
        btnEditCusAcc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditCusAcc.addActionListener(this::btnEditCusAccActionPerformed);

        javax.swing.GroupLayout pnlcusLayout = new javax.swing.GroupLayout(pnlcus);
        pnlcus.setLayout(pnlcusLayout);
        pnlcusLayout.setHorizontalGroup(
            pnlcusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlcusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlcusLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(imagePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFindCusAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(51, 51, 51))
                    .addGroup(pnlcusLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(129, Short.MAX_VALUE))))
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddCusAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditCusAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteCusAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        pnlcusLayout.setVerticalGroup(
            pnlcusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlcusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlcusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFindCusAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlcusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCusAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCusAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCusAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout pnlCustomerAccountLayout = new javax.swing.GroupLayout(pnlCustomerAccount);
        pnlCustomerAccount.setLayout(pnlCustomerAccountLayout);
        pnlCustomerAccountLayout.setHorizontalGroup(
            pnlCustomerAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
            .addGroup(pnlCustomerAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCustomerAccountLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlcus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        pnlCustomerAccountLayout.setVerticalGroup(
            pnlCustomerAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
            .addGroup(pnlCustomerAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCustomerAccountLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlcus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlCustomerAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlCustomerAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteCusAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCusAccActionPerformed
//        int selectedRow = tblCustomerAccount.getSelectedRow();
//
//        if (selectedRow == -1) {
//            JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản cần xóa!");
//            return;
//        }
//
//        // 1. Lấy Username từ cột đầu tiên (Index 0) để hiển thị thông báo
//        String username = tblCustomerAccount.getValueAt(selectedRow, 0).toString();
//
//        // 2. Lấy AccountID từ cột thứ hai (Index 1) để dùng làm điều kiện xóa trong SQL
//        int accountId = Integer.parseInt(tblCustomerAccount.getValueAt(selectedRow, 1).toString());
//
//        // 3. Thông báo hiển thị tên Username cho thân thiện
//        int confirm = JOptionPane.showConfirmDialog(this,
//                "Bạn có chắc chắn muốn xóa tài khoản: " + username + " không?",
//                "Xác nhận xóa",
//                JOptionPane.YES_NO_OPTION,
//                JOptionPane.QUESTION_MESSAGE);
//
//        if (confirm == JOptionPane.YES_OPTION) {
//            AccountDAO dao = new AccountDAO();
//
//            // Gọi hàm xóa vĩnh viễn bằng ID
//            if (dao.deleteAccount(accountId)) {
//                JOptionPane.showMessageDialog(this, "Đã xóa tài khoản " + username + " thành công!");
//                adminController.loadDataToTableCustomerAccount(tblCustomerAccount);
//            } else {
//                JOptionPane.showMessageDialog(this, "Lỗi! Không thể xóa tài khoản này.");
//            }
//        }
    }//GEN-LAST:event_btnDeleteCusAccActionPerformed

    private void btnAddCusAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCusAccActionPerformed
        // 1. Khởi tạo dialog (truyền vào Frame cha)
        Frame parent = (Frame) SwingUtilities.getWindowAncestor(this);
        AccountDialog dialog = new AccountDialog(parent);

        // 2. Hiển thị dialog (nó sẽ dừng code ở đây cho đến khi dialog đóng)
        dialog.setVisible(true);

        // 3. Nếu bấm "Lưu" thành công thì mới xử lý tiếp
        if (dialog.isSucceeded()) {
            AccountModel newAcc = dialog.getAccountData();

            // 4. Gọi DAO để lưu vào 2 bảng (Dùng hàm insertAccount mình đã viết ở trên)
            if (accountDAO.insertAccount(newAcc)) {
                JOptionPane.showMessageDialog(this, "Thêm tài khoản thành công!");
                // Load lại bảng
                adminController.loadDataToTableAdminAccount(tblAdminAccount);
                adminController.loadDataToTableCustomerAccount(tblCustomerAccount);
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại! Kiểm tra lại SĐT hoặc Username.");
            }
        }
    }//GEN-LAST:event_btnAddCusAccActionPerformed

    private void btnEditCusAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCusAccActionPerformed
        int row = tblAdminAccount.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản cần sửa!");
            return;
        }

        try {
            // 1. Bốc dữ liệu trực tiếp từ các cột theo hình Huy gửi
            String username = tblAdminAccount.getValueAt(row, 0).toString();
            int accountId = Integer.parseInt(tblAdminAccount.getValueAt(row, 1).toString());
            String fullName = tblAdminAccount.getValueAt(row, 2).toString();
            String sdt = tblAdminAccount.getValueAt(row, 3).toString();
            String diaChi = tblAdminAccount.getValueAt(row, 4).toString();
            String ngaySinhStr = tblAdminAccount.getValueAt(row, 5).toString();
            String gioiTinh = tblAdminAccount.getValueAt(row, 6).toString();
            String trangThai = tblAdminAccount.getValueAt(row, 8).toString();

            // 2. Tạo đối tượng tạm thời để đổ lên Dialog
            UserModel u = new UserModel();
            u.setFullName(fullName);
            u.setSDT(sdt);
            u.setAddress(diaChi);
            u.setGioiTinh(gioiTinh);

            try {
                u.setNgaySinh(java.sql.Date.valueOf(ngaySinhStr));
            } catch (Exception e) {

            }

            AccountModel selectedAcc = new AccountModel();
            selectedAcc.setAccountId(accountId);
            selectedAcc.setUsername(username);
            selectedAcc.setUserInfo(u);
            selectedAcc.setStatus(trangThai);

            // 3. Mở Dialog
            AccountDialog dialog = new AccountDialog((java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this));
            dialog.setModel(selectedAcc);
            dialog.setVisible(true);

            // 4. Xử lý sau khi người dùng bấm "CẬP NHẬT"
            if (dialog.isSucceeded()) {
                AccountModel updatedData = dialog.getAccountData();

                // QUAN TRỌNG: Vì bốc từ bảng không có USER_ID, Huy cần lấy nó từ listAccount hoặc DB
                // Để đơn giản và chính xác nhất, mình tìm lại USER_ID dựa vào AccountID trong DB
                int realUserId = accountDAO.getUserIdByAccountId(accountId);
                updatedData.setUserId(realUserId);
                updatedData.setAccountId(accountId);

                if (accountDAO.updateAccount(updatedData)) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                    adminController.loadDataToTableAdminAccount(tblAdminAccount);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi lấy dữ liệu từ bảng!");
        }
    }//GEN-LAST:event_btnEditCusAccActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom_Component.MyButton btnAddCusAcc;
    private Custom_Component.MyButton btnDeleteCusAcc;
    private Custom_Component.MyButton btnEditCusAcc;
    private Custom_Component.ImagePanel imagePanel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlCustomerAccount;
    private javax.swing.JPanel pnlcus;
    private javax.swing.JTable tblCustomerAccount;
    private Custom_Component.MyTextField txtFindCusAccount;
    // End of variables declaration//GEN-END:variables
}
