/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.panel.admin;

import Controller.ProductController;
import Controller.adminPageController;
import DAO.ProductDAO;
import Model.ProductModel;
import Util.AppConst;
import Util.TableDecorate;
import Util.UserSession;
import View.dialog.ChiTietSanPhamDialog;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author HUY0406
 */
public class panelSanpham extends javax.swing.JPanel {

    /**
     * Creates new form pnlSanPham
     */
    private ProductController productController = new ProductController();
    private adminPageController adminController = new adminPageController();
    List<ProductModel> currentList;

    public panelSanpham() {
        initComponents();
        productController.loadAllProductsToTable(tblProduct, this);

        //SetUpTable
        adminController.setUpTable(tblProduct, 8);
        TableDecorate.StatusRenderer statusRenderer = new TableDecorate.StatusRenderer();
        tblProduct.getColumnModel().getColumn(7).setCellRenderer(statusRenderer); //cho cột trạng thái đẹp hơn

        //ComboBox
        productController.updateDataCategoryCbx(cbxCategory);

//        checkPermission();
    }

    private void showPanel(JPanel panel) {
        this.removeAll();
        this.setLayout(new java.awt.BorderLayout());
        this.add(panel, java.awt.BorderLayout.CENTER);

        this.revalidate();
        this.repaint();
    }

    public void setCurrentList(List<ProductModel> list) {
        this.currentList = list;
    }

    private void executeFilter() {
        //search
        String search = txtSearch.getText().trim();
        //category
        Object selectedCat = cbxCategory.getSelectedItem();
        String category = (selectedCat == null) ? "" : selectedCat.toString();
        //status
        Object selectedStatus = cbxStatus.getSelectedItem();
        String status = (selectedStatus == null) ? "" : selectedStatus.toString();

        if (currentList == null) {
            return;
        }
        productController.filterProducts(tblProduct, currentList, search, category, status);
    }

    public void updateSummaryLabels(List<ProductModel> list) {
        int tongSP = 0;
        int sapHetHang = 0;
        int maxBan = 0;
        String tenBanChay = "Chưa có"; // Nếu chưa bán được gì thì hiện chữ này

        if (list != null && !list.isEmpty()) {
            tongSP = list.size();
            for (ProductModel p : list) {
                // 1. Đếm sản phẩm sắp hết hàng (tồn < 5)
                if (p.getStockQuantity() < 5) {
                    sapHetHang++;
                }

                // 2. Tìm sản phẩm có số lượng bán cao nhất (Sold Quantity)
                if (p.getSoldQuantity() > maxBan) {
                    maxBan = p.getSoldQuantity();
                    tenBanChay = p.getName();
                }
            }
        }

        // --- Đổ dữ liệu lên Dashboard ---
        // Tổng số sản phẩm (Số 1 trong hình cũ)
        lblTongSP.setText(String.valueOf(tongSP));

        // Số sản phẩm sắp hết (Số 1 trong hình cũ)
        lblSapHetHang.setText(String.valueOf(sapHetHang));

        // --- PHẦN BA CẦN (Sản phẩm bán chạy nhất) ---
        // Thay số 1 to đùng bằng Tên Sản Phẩm (như hình image_a30176.png)
        lblTenSPBanChay.setText(tenBanChay);

        // Thay xxx bằng số lượng đã bán thật (như hình image_a30535.png)
        lblSoLuongBanChay.setText("Số lượng bán ra: " + maxBan + " sản phẩm");
    }

//    public void checkPermission() {
//        // 1. Lấy tên chức năng của Panel này (Ví dụ: Quản lý sản phẩm)
//        String feature = AppConst.QL_SAN_PHAM;
//
//        // 2. Kiểm tra quyền VIEW (Quyền tối thiểu để thấy giao diện)
//        if (UserSession.canDo(feature, AppConst.ACTION_VIEW) == 0) {
//            this.setVisible(false);
//            return;
//        }
//
//        // 3. Kiểm tra các nút bấm cụ thể
//        // setEnabled(true/false) sẽ làm nút sáng lên hoặc mờ đi
//        btnAddProduct.setEnabled(UserSession.canDo(feature, AppConst.ACTION_ADD) == 1);
//        btnEditProduct.setEnabled(UserSession.canDo(feature, AppConst.ACTION_EDIT) == 1);
//        btnDeleteProduct.setEnabled(UserSession.canDo(feature, AppConst.ACTION_DELETE) == 1);
//
    ////        // Nếu có nút Xuất Excel/PDF thì check quyền DOWNLOAD
////        if (btnExport != null) {
////            btnExport.setEnabled(UserSession.canDo(feature, AppConst.ACTION_DOWNLOAD) == 1);
////        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myTextField2 = new Custom_Component.MyTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        pnlAdminAccount = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtSearch = new Custom_Component.MyTextField();
        cbxCategory = new javax.swing.JComboBox<>();
        cbxStatus = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTongSP = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblSoLuongBanChay = new javax.swing.JLabel();
        lblTenSPBanChay = new javax.swing.JLabel();
        lblSapHetHang = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        myButton1 = new Custom_Component.MyButton();
        lblReload = new javax.swing.JLabel();

        myTextField2.setText("myTextField2");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel11.setText("jLabel11");

        pnlAdminAccount.setBackground(new java.awt.Color(255, 255, 255));
        pnlAdminAccount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Quản lý sản phẩm");

        tblProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Danh mục", "Thương hiệu", "Giá bán", "Số lượng tồn kho", "Số lượng đã bán", "Trạng thái", "Image", "Mô tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduct.setGridColor(new java.awt.Color(204, 204, 204));
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduct);
        if (tblProduct.getColumnModel().getColumnCount() > 0) {
            tblProduct.getColumnModel().getColumn(8).setMinWidth(0);
            tblProduct.getColumnModel().getColumn(8).setPreferredWidth(0);
            tblProduct.getColumnModel().getColumn(8).setMaxWidth(0);
            tblProduct.getColumnModel().getColumn(9).setMinWidth(0);
            tblProduct.getColumnModel().getColumn(9).setPreferredWidth(0);
            tblProduct.getColumnModel().getColumn(9).setMaxWidth(0);
        }

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtSearch.addActionListener(this::txtSearchActionPerformed);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        cbxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Lọc theo danh mục--" }));
        cbxCategory.addActionListener(this::cbxCategoryActionPerformed);

        cbxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Lọc theo trạng thái--", "Đang bán", "Ngừng kinh doanh", "Hết hàng" }));
        cbxStatus.addActionListener(this::cbxStatusActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Số liệu tổng quát"));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 200));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tổng số sản phẩm ");

        lblTongSP.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTongSP.setText("1");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Số sản phẩm sắp hết hàng");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel5.setText("sản phẩm");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setText("sản phẩm");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Sản phẩm bán chạy nhất");

        lblSoLuongBanChay.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblSoLuongBanChay.setText("Số lượng bán ra: xxx sản phẩm");

        lblTenSPBanChay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTenSPBanChay.setText("Tên sản phẩm");

        lblSapHetHang.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblSapHetHang.setText("1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTongSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(73, 73, 73)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(23, 23, 23)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(122, 348, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSapHetHang, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(244, 244, 244))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 705, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenSPBanChay, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSoLuongBanChay, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTongSP, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addComponent(lblSapHetHang))
                    .addComponent(lblTenSPBanChay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSoLuongBanChay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.add(jPanel1, new java.awt.GridBagConstraints());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Tìm kiếm và lọc sản phẩm");

        myButton1.setBackground(new java.awt.Color(255, 102, 0));
        myButton1.setForeground(new java.awt.Color(255, 255, 255));
        myButton1.setText("Nhập hàng mới +");
        myButton1.setColorClick(new java.awt.Color(204, 82, 0));
        myButton1.setColorHover(new java.awt.Color(255, 128, 51));
        myButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        myButton1.addActionListener(this::myButton1ActionPerformed);

        lblReload.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblReload.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-reload-24.png"))); // NOI18N
        lblReload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReloadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminAccountLayout = new javax.swing.GroupLayout(pnlAdminAccount);
        pnlAdminAccount.setLayout(pnlAdminAccountLayout);
        pnlAdminAccountLayout.setHorizontalGroup(
            pnlAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(pnlAdminAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminAccountLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(494, 494, 494))
                    .addGroup(pnlAdminAccountLayout.createSequentialGroup()
                        .addGroup(pnlAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlAdminAccountLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(527, 527, 527)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(lblReload, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pnlAdminAccountLayout.setVerticalGroup(
            pnlAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminAccountLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlAdminAccountLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAdminAccountLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pnlAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReload, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1092, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlAdminAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1075, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlAdminAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        panelNhapHang pnlNhap = new panelNhapHang();
        showPanel(pnlNhap);
    }//GEN-LAST:event_myButton1ActionPerformed

    private void lblReloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReloadMouseClicked
        productController.loadAllProductsToTable(tblProduct, this);
    }//GEN-LAST:event_lblReloadMouseClicked

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        if (evt.getClickCount() == 2) { // Double click để xem chi tiết
            int row = tblProduct.getSelectedRow();
            if (row != -1) {
                // Lấy dữ liệu từ các cột 
                int id = Integer.parseInt(tblProduct.getValueAt(row, 0).toString());
                String ten = tblProduct.getValueAt(row, 1).toString();
                String danhMuc = tblProduct.getValueAt(row, 2).toString();
                String thuongHieu = tblProduct.getValueAt(row, 3).toString();
                String gia = tblProduct.getValueAt(row, 4).toString();
                String soLuongTon = tblProduct.getValueAt(row, 5).toString();
                String trangThai = tblProduct.getValueAt(row, 7).toString();
                Object imgObj = tblProduct.getValueAt(row, 8);
                String hinhAnh = (imgObj != null) ? imgObj.toString() : "";
                Object descObj = tblProduct.getValueAt(row, 9);
                String moTa = (descObj != null) ? descObj.toString() : "Không có mô tả";

                // Khởi tạo Dialog
                ChiTietSanPhamDialog dialog = new ChiTietSanPhamDialog(null, true);
                dialog.fillData(id, ten, gia, danhMuc, thuongHieu, moTa, trangThai, hinhAnh, soLuongTon);

                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);

                executeFilter();
            }
        }
    }//GEN-LAST:event_tblProductMouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        executeFilter();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void cbxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoryActionPerformed
        executeFilter();
    }//GEN-LAST:event_cbxCategoryActionPerformed

    private void cbxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxStatusActionPerformed
        executeFilter();
    }//GEN-LAST:event_cbxStatusActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxCategory;
    private javax.swing.JComboBox<String> cbxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblReload;
    private javax.swing.JLabel lblSapHetHang;
    private javax.swing.JLabel lblSoLuongBanChay;
    private javax.swing.JLabel lblTenSPBanChay;
    private javax.swing.JLabel lblTongSP;
    private Custom_Component.MyButton myButton1;
    private Custom_Component.MyTextField myTextField2;
    private javax.swing.JPanel pnlAdminAccount;
    private javax.swing.JTable tblProduct;
    private Custom_Component.MyTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
