/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.panel.admin;

import Controller.AdminAccountController;
import Util.TableDecorate;
import Controller.adminPageController;
import DAO.AccountDAO;
import Model.AccountModel;
import Model.UserModel;
import View.User.AdminForm;
import View.dialog.AccountDialog;
import View.dialog.TaiKhoanAdminDialog;
import View.dialog.dialogThemQuyen;
import java.awt.Frame;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author phamd
 */
public class panelTaikhoan extends javax.swing.JPanel {

    private adminPageController adminController = new adminPageController();
    private TableDecorate tableAction = new TableDecorate();
    private AccountDAO accountDAO = new AccountDAO();
    private AdminAccountController controller = new AdminAccountController();

    /**
     * Creates new form panelTaikhoan
     */
    public panelTaikhoan() {
        initComponents();

        //Admin account
        controller.loadDataToTable(tblAdminAccount);
        adminController.setUpTable(tblAdminAccount, 11);

        //Decorate Table
        TableDecorate.StatusRenderer statusRenderer = new TableDecorate.StatusRenderer();
        tblAdminAccount.getColumnModel().getColumn(9).setCellRenderer(statusRenderer); //cho cột trạng thái đẹp hơn

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlAdminAccount = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdminAccount = new javax.swing.JTable();
        txtFindAccount = new Custom_Component.MyTextField();
        imagePanel1 = new Custom_Component.ImagePanel();
        btnDeleteAcc = new Custom_Component.MyButton();
        btnAddAcc = new Custom_Component.MyButton();
        btnEditAcc = new Custom_Component.MyButton();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("QUẢN LÝ TÀI KHOẢN");

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        pnlAdminAccount.setBackground(new java.awt.Color(255, 255, 255));
        pnlAdminAccount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Danh Sách Tài Khoản Admin & Nhân Viên Trong Hệ Thống");

        tblAdminAccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblAdminAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên đăng nhập", "Họ và tên", "SĐT", "Email", "Địa chỉ", "Ngày sinh", "Giới tính", "Loại tài khoản", "Vai trò", "Trạng thái", "AccountID", "userId"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAdminAccount.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tblAdminAccount);
        if (tblAdminAccount.getColumnModel().getColumnCount() > 0) {
            tblAdminAccount.getColumnModel().getColumn(10).setMinWidth(0);
            tblAdminAccount.getColumnModel().getColumn(10).setPreferredWidth(0);
            tblAdminAccount.getColumnModel().getColumn(10).setMaxWidth(0);
            tblAdminAccount.getColumnModel().getColumn(11).setMinWidth(0);
            tblAdminAccount.getColumnModel().getColumn(11).setPreferredWidth(0);
            tblAdminAccount.getColumnModel().getColumn(11).setMaxWidth(0);
        }

        imagePanel1.setImage(new javax.swing.ImageIcon(getClass().getResource("/Resource/search.png"))); // NOI18N

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnDeleteAcc.setBackground(new java.awt.Color(255, 51, 51));
        btnDeleteAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteAcc.setText("Xóa tài khoản");
        btnDeleteAcc.setColorClick(new java.awt.Color(0, 0, 255));
        btnDeleteAcc.setColorHover(new java.awt.Color(51, 102, 255));
        btnDeleteAcc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteAcc.addActionListener(this::btnDeleteAccActionPerformed);

        btnAddAcc.setBackground(new java.awt.Color(51, 51, 255));
        btnAddAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnAddAcc.setText("Thêm tài khoản");
        btnAddAcc.setColorClick(new java.awt.Color(0, 0, 255));
        btnAddAcc.setColorHover(new java.awt.Color(51, 102, 255));
        btnAddAcc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddAcc.addActionListener(this::btnAddAccActionPerformed);

        btnEditAcc.setBackground(new java.awt.Color(51, 51, 255));
        btnEditAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnEditAcc.setText("Sửa tài khoản");
        btnEditAcc.setColorClick(new java.awt.Color(0, 0, 255));
        btnEditAcc.setColorHover(new java.awt.Color(51, 102, 255));
        btnEditAcc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditAcc.addActionListener(this::btnEditAccActionPerformed);

        javax.swing.GroupLayout pnlAdminAccountLayout = new javax.swing.GroupLayout(pnlAdminAccount);
        pnlAdminAccount.setLayout(pnlAdminAccountLayout);
        pnlAdminAccountLayout.setHorizontalGroup(
            pnlAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminAccountLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(imagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFindAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminAccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(pnlAdminAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        pnlAdminAccountLayout.setVerticalGroup(
            pnlAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFindAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jTabbedPane1.addTab("Tài khoản Admin & Nhân viên", pnlAdminAccount);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAccActionPerformed
        int row = tblAdminAccount.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Ba vui lòng chọn 1 tài khoản trong bảng để sửa!");
            return;
        }

        // 1. Lấy dữ liệu từ bảng nhét vào Model (Dựa trên 12 cột ba đã set)
        AccountModel acc = new AccountModel();
        UserModel user = new UserModel();

        acc.setUsername(tblAdminAccount.getValueAt(row, 0).toString());
        user.setFullName(tblAdminAccount.getValueAt(row, 1).toString());
        user.setSDT(tblAdminAccount.getValueAt(row, 2).toString());
        user.setEmail(tblAdminAccount.getValueAt(row, 3).toString());
        user.setAddress(tblAdminAccount.getValueAt(row, 4).toString());

        // Xử lý ngày sinh từ bảng (String -> Date)
        try {
            String dateStr = tblAdminAccount.getValueAt(row, 5).toString();
            java.util.Date d = new java.text.SimpleDateFormat("dd/MM/yyyy").parse(dateStr);
            user.setNgaySinh(new java.sql.Date(d.getTime()));
        } catch (Exception e) {
        }

        user.setGioiTinh(tblAdminAccount.getValueAt(row, 6).toString());
        user.setUserType(tblAdminAccount.getValueAt(row, 7).toString().equals("Quản trị viên") ? "ADMIN" : "STAFF");
        acc.setStatus(tblAdminAccount.getValueAt(row, 9).toString().equals("Hoạt động") ? 1 : 0);

        // Lấy 2 ID ẩn ở cuối bảng
        acc.setAccountId((int) tblAdminAccount.getValueAt(row, 10));
        user.setUserId((int) tblAdminAccount.getValueAt(row, 11));

        acc.setUserInfo(user);

        // 2. Mở Dialog ở chế độ Sửa
        TaiKhoanAdminDialog dialog = new TaiKhoanAdminDialog(null, true);
        dialog.setEditMode(acc); // Truyền model vào để đổ dữ liệu lên form
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);

        // 3. Load lại bảng
        controller.loadDataToTable(tblAdminAccount);
    }//GEN-LAST:event_btnEditAccActionPerformed

    private void btnAddAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAccActionPerformed
        TaiKhoanAdminDialog dialog = new TaiKhoanAdminDialog(null, true);
        dialog.setAddMode(); // Gọi hàm xóa trắng form
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);

        // Sau khi đóng dialog, load lại bảng
        controller.loadDataToTable(tblAdminAccount);
    }//GEN-LAST:event_btnAddAccActionPerformed

    private void btnDeleteAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAccActionPerformed
// 1. Kiểm tra xem người dùng đã chọn dòng nào chưa
        int row = tblAdminAccount.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Ba vui lòng chọn một tài khoản trong bảng để xóa!");
            return;
        }

        // 2. Lấy thông tin để hiển thị xác nhận
        String username = tblAdminAccount.getValueAt(row, 0).toString();
        int accountId = (int) tblAdminAccount.getValueAt(row, 10); // Lấy ID từ cột ẩn số 10

        // 3. Hỏi xác nhận trước khi xóa (Cho chắc ăn ba ạ)
        int confirm = JOptionPane.showConfirmDialog(this,
                "Ba có chắc chắn muốn xóa tài khoản [" + username + "] không?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            // 4. Gọi Controller thực hiện xóa
            if (accountDAO.deleteAccount(accountId)) {
                JOptionPane.showMessageDialog(this, "Đã xóa tài khoản thành công!");
                // 5. Load lại bảng để cập nhật dữ liệu mới
                controller.loadDataToTable(tblAdminAccount);
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi! Không thể xóa tài khoản này.");
            }
        }
    }//GEN-LAST:event_btnDeleteAccActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom_Component.MyButton btnAddAcc;
    private Custom_Component.MyButton btnDeleteAcc;
    private Custom_Component.MyButton btnEditAcc;
    private Custom_Component.ImagePanel imagePanel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlAdminAccount;
    private javax.swing.JTable tblAdminAccount;
    private Custom_Component.MyTextField txtFindAccount;
    // End of variables declaration//GEN-END:variables
}
