/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.AdminForm;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author phamd
 */
public class AdminForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminForm.class.getName());
    private javax.swing.JLabel currentSelectedLabel = null;

    /**
     * Creates new form Main
     */
    public AdminForm() {
        initComponents();
        btnDoanhSo.setVisible(false);
        btnThongke.setVisible(false);
        showPanel(new panelTrangchu());
        resetMenuButtons(btnTrangchu);

    }

    private void showPanel(JPanel panel) {
        panelView.removeAll();
        panelView.setLayout(new java.awt.BorderLayout());
        panelView.add(panel, java.awt.BorderLayout.CENTER);

        panelView.revalidate();
        panelView.repaint();
    }

    private void resetMenuButtons(javax.swing.JLabel activeLabel) {
        currentSelectedLabel = activeLabel;
        if (activeLabel == btnTrangchu) {
            btnArrowTrangchu.setOpaque(true);
            btnArrowTrangchu.setBackground(new Color(30, 30, 80));
        } else {
            btnArrowTrangchu.setOpaque(false);
        }
        javax.swing.JLabel[] labels = {btnTrangchu, btnDoanhSo, btnThongke, btnBanhang, btnSanpham, btnHoadon, btnKhuyenmai, btnTaikhoan, btnRole, btnLogout};

        for (javax.swing.JLabel lbl : labels) {
            if (lbl == activeLabel) {
                // Nút được chọn: Màu cam san hô và có nền xám nhạt
                lbl.setForeground(Color.WHITE);
                lbl.setOpaque(true);
                lbl.setBackground(new Color(30, 30, 80));
                lbl.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                        // Lớp ngoài: Thanh dọc màu xanh dương dày 4px sát lề trái
                        javax.swing.BorderFactory.createMatteBorder(0, 4, 0, 0, new Color(0, 153, 255)),
                        // Lớp trong: Khoảng trống tàng hình 20px để đẩy Icon ra xa thanh xanh dương
                        javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0)
                ));

            } else {
                // Các nút còn lại: Trả về màu xám mặc định và trong suốt
                lbl.setForeground(new Color(153, 153, 153));
                lbl.setOpaque(false);
                lbl.setBackground(new Color(255, 255, 255));
                lbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 4, 0, 0));
            }
        }
        btnArrowTrangchu.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Layout = new javax.swing.JPanel();
        panelView = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        RoleName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Title2 = new javax.swing.JLabel();
        btnTrangchu = new javax.swing.JLabel();
        btnArrowTrangchu = new javax.swing.JLabel();
        btnBanhang = new javax.swing.JLabel();
        btnSanpham = new javax.swing.JLabel();
        btnHoadon = new javax.swing.JLabel();
        btnKhuyenmai = new javax.swing.JLabel();
        btnTaikhoan = new javax.swing.JLabel();
        btnDoanhSo = new javax.swing.JLabel();
        btnThongke = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        btnRole = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        Layout.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
        panelView.setLayout(panelViewLayout);
        panelViewLayout.setHorizontalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );
        panelViewLayout.setVerticalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Menu.setBackground(new java.awt.Color(0, 0, 51));
        Menu.setPreferredSize(new java.awt.Dimension(215, 452));

        title.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 102, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("SMART HUB");

        RoleName.setBackground(new java.awt.Color(0, 0, 51));
        RoleName.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        RoleName.setForeground(new java.awt.Color(153, 153, 153));
        RoleName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RoleName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/8.png"))); // NOI18N
        RoleName.setText("ADMIN");
        RoleName.setOpaque(true);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        Title2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Title2.setForeground(new java.awt.Color(255, 255, 255));
        Title2.setText("   Quản lý");

        btnTrangchu.setBackground(new java.awt.Color(0, 0, 51));
        btnTrangchu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnTrangchu.setForeground(new java.awt.Color(153, 153, 153));
        btnTrangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1.png"))); // NOI18N
        btnTrangchu.setText("Trang chủ");
        btnTrangchu.setFocusable(false);
        btnTrangchu.setIconTextGap(15);
        btnTrangchu.setMaximumSize(new java.awt.Dimension(105, 40));
        btnTrangchu.setMinimumSize(new java.awt.Dimension(105, 40));
        btnTrangchu.setOpaque(true);
        btnTrangchu.setPreferredSize(new java.awt.Dimension(82, 50));
        btnTrangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrangchuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrangchuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrangchuMouseExited(evt);
            }
        });

        btnArrowTrangchu.setForeground(new java.awt.Color(255, 255, 255));
        btnArrowTrangchu.setText("▼");
        btnArrowTrangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnArrowTrangchuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnArrowTrangchuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnArrowTrangchuMouseExited(evt);
            }
        });

        btnBanhang.setBackground(new java.awt.Color(0, 0, 51));
        btnBanhang.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnBanhang.setForeground(new java.awt.Color(153, 153, 153));
        btnBanhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/2.png"))); // NOI18N
        btnBanhang.setText("Bán hàng tại quầy");
        btnBanhang.setFocusable(false);
        btnBanhang.setIconTextGap(15);
        btnBanhang.setOpaque(true);
        btnBanhang.setPreferredSize(new java.awt.Dimension(82, 50));
        btnBanhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBanhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBanhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBanhangMouseExited(evt);
            }
        });

        btnSanpham.setBackground(new java.awt.Color(0, 0, 51));
        btnSanpham.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSanpham.setForeground(new java.awt.Color(153, 153, 153));
        btnSanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/5.png"))); // NOI18N
        btnSanpham.setText("Quản lý sản phẩm");
        btnSanpham.setFocusable(false);
        btnSanpham.setIconTextGap(15);
        btnSanpham.setOpaque(true);
        btnSanpham.setPreferredSize(new java.awt.Dimension(82, 50));
        btnSanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSanphamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSanphamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSanphamMouseExited(evt);
            }
        });

        btnHoadon.setBackground(new java.awt.Color(0, 0, 51));
        btnHoadon.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnHoadon.setForeground(new java.awt.Color(153, 153, 153));
        btnHoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/7.png"))); // NOI18N
        btnHoadon.setText("Quản lý Đơn Hàng");
        btnHoadon.setFocusable(false);
        btnHoadon.setIconTextGap(15);
        btnHoadon.setOpaque(true);
        btnHoadon.setPreferredSize(new java.awt.Dimension(82, 50));
        btnHoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHoadonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHoadonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHoadonMouseExited(evt);
            }
        });

        btnKhuyenmai.setBackground(new java.awt.Color(0, 0, 51));
        btnKhuyenmai.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnKhuyenmai.setForeground(new java.awt.Color(153, 153, 153));
        btnKhuyenmai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/3.png"))); // NOI18N
        btnKhuyenmai.setText("Quản lý Khuyến mãi");
        btnKhuyenmai.setFocusable(false);
        btnKhuyenmai.setIconTextGap(15);
        btnKhuyenmai.setOpaque(true);
        btnKhuyenmai.setPreferredSize(new java.awt.Dimension(82, 50));
        btnKhuyenmai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKhuyenmaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKhuyenmaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKhuyenmaiMouseExited(evt);
            }
        });

        btnTaikhoan.setBackground(new java.awt.Color(0, 0, 51));
        btnTaikhoan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnTaikhoan.setForeground(new java.awt.Color(153, 153, 153));
        btnTaikhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/8.png"))); // NOI18N
        btnTaikhoan.setText("Quản lý Tài khoản");
        btnTaikhoan.setFocusable(false);
        btnTaikhoan.setIconTextGap(15);
        btnTaikhoan.setOpaque(true);
        btnTaikhoan.setPreferredSize(new java.awt.Dimension(82, 50));
        btnTaikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTaikhoanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTaikhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTaikhoanMouseExited(evt);
            }
        });

        btnDoanhSo.setBackground(new java.awt.Color(0, 0, 51));
        btnDoanhSo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnDoanhSo.setForeground(new java.awt.Color(153, 153, 153));
        btnDoanhSo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/6.png"))); // NOI18N
        btnDoanhSo.setText("Doanh Số");
        btnDoanhSo.setFocusable(false);
        btnDoanhSo.setIconTextGap(15);
        btnDoanhSo.setOpaque(true);
        btnDoanhSo.setPreferredSize(new java.awt.Dimension(82, 50));
        btnDoanhSo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoanhSoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDoanhSoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDoanhSoMouseExited(evt);
            }
        });

        btnThongke.setBackground(new java.awt.Color(255, 255, 255));
        btnThongke.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnThongke.setForeground(new java.awt.Color(153, 153, 153));
        btnThongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/4.png"))); // NOI18N
        btnThongke.setText("Thống kê");
        btnThongke.setFocusable(false);
        btnThongke.setIconTextGap(15);
        btnThongke.setMaximumSize(new java.awt.Dimension(100, 40));
        btnThongke.setMinimumSize(new java.awt.Dimension(100, 40));
        btnThongke.setPreferredSize(new java.awt.Dimension(82, 50));
        btnThongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThongkeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThongkeMouseExited(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(0, 0, 51));
        btnLogout.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(153, 153, 153));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/9.png"))); // NOI18N
        btnLogout.setText("Log Out");
        btnLogout.setFocusable(false);
        btnLogout.setIconTextGap(15);
        btnLogout.setOpaque(true);
        btnLogout.setPreferredSize(new java.awt.Dimension(82, 50));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });

        btnRole.setBackground(new java.awt.Color(0, 0, 51));
        btnRole.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnRole.setForeground(new java.awt.Color(153, 153, 153));
        btnRole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/8.png"))); // NOI18N
        btnRole.setText("Phân quyền");
        btnRole.setFocusable(false);
        btnRole.setIconTextGap(15);
        btnRole.setOpaque(true);
        btnRole.setPreferredSize(new java.awt.Dimension(82, 50));
        btnRole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRoleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRoleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRoleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Title2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addComponent(RoleName)
                        .addGap(22, 22, 22)
                        .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8))
                    .addComponent(btnTaikhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKhuyenmai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHoadon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBanhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                        .addComponent(btnDoanhSo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addComponent(btnTrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btnArrowTrangchu, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addComponent(btnThongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTrangchu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnArrowTrangchu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThongke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDoanhSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBanhang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Title2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoleName)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LayoutLayout = new javax.swing.GroupLayout(Layout);
        Layout.setLayout(LayoutLayout);
        LayoutLayout.setHorizontalGroup(
            LayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LayoutLayout.setVerticalGroup(
            LayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
            .addComponent(panelView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Layout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Layout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrangchuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangchuMouseEntered
        if (btnTrangchu != currentSelectedLabel) {
            btnTrangchu.setOpaque(true);
            btnTrangchu.setBackground(new Color(30, 30, 80));
            btnTrangchu.setForeground(Color.WHITE);

            btnArrowTrangchu.setOpaque(true);
            btnArrowTrangchu.setBackground(new Color(30, 30, 80));
            btnTrangchu.repaint();
            btnArrowTrangchu.repaint();
        }
    }//GEN-LAST:event_btnTrangchuMouseEntered

    private void btnTrangchuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangchuMouseExited
        if (btnTrangchu != currentSelectedLabel) {
            btnTrangchu.setOpaque(false);
            btnTrangchu.setForeground(new Color(153, 153, 153));

            btnArrowTrangchu.setOpaque(false);
            btnTrangchu.repaint();
            btnArrowTrangchu.repaint();
        }
    }//GEN-LAST:event_btnTrangchuMouseExited

    private void btnBanhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanhangMouseEntered
        if (btnBanhang != currentSelectedLabel) {
            btnBanhang.setOpaque(true);
            btnBanhang.setBackground(new Color(30, 30, 80));
            btnBanhang.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_btnBanhangMouseEntered

    private void btnBanhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanhangMouseExited
        if (btnBanhang != currentSelectedLabel) {
            btnBanhang.setOpaque(false);
            btnBanhang.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_btnBanhangMouseExited

    private void btnSanphamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanphamMouseEntered
        if (btnSanpham != currentSelectedLabel) {
            btnSanpham.setOpaque(true);
            btnSanpham.setBackground(new Color(30, 30, 80));
            btnSanpham.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_btnSanphamMouseEntered

    private void btnSanphamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanphamMouseExited
        if (btnSanpham != currentSelectedLabel) {
            btnSanpham.setOpaque(false); // Trả về trong suốt
            btnSanpham.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_btnSanphamMouseExited

    private void btnHoadonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoadonMouseEntered
        if (btnHoadon != currentSelectedLabel) {
            btnHoadon.setOpaque(true);
            btnHoadon.setBackground(new Color(30, 30, 80));
            btnHoadon.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_btnHoadonMouseEntered

    private void btnHoadonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoadonMouseExited
        if (btnHoadon != currentSelectedLabel) {
            btnHoadon.setOpaque(false); // Trả về trong suốt
            btnHoadon.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_btnHoadonMouseExited

    private void btnKhuyenmaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhuyenmaiMouseEntered
        if (btnKhuyenmai != currentSelectedLabel) {
            btnKhuyenmai.setOpaque(true);
            btnKhuyenmai.setBackground(new Color(30, 30, 80));
            btnKhuyenmai.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_btnKhuyenmaiMouseEntered

    private void btnKhuyenmaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhuyenmaiMouseExited
        if (btnKhuyenmai != currentSelectedLabel) {
            btnKhuyenmai.setOpaque(false); // Trả về trong suốt
            btnKhuyenmai.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_btnKhuyenmaiMouseExited

    private void btnTaikhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaikhoanMouseEntered
        if (btnTaikhoan != currentSelectedLabel) {
            btnTaikhoan.setOpaque(true);
            btnTaikhoan.setBackground(new Color(30, 30, 80));
            btnTaikhoan.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_btnTaikhoanMouseEntered

    private void btnTaikhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaikhoanMouseExited
        if (btnTaikhoan != currentSelectedLabel) {
            btnTaikhoan.setOpaque(false); // Trả về trong suốt
            btnTaikhoan.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_btnTaikhoanMouseExited

    private void btnDoanhSoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoanhSoMouseEntered
        if (btnDoanhSo != currentSelectedLabel) {
            btnDoanhSo.setOpaque(true);
            btnDoanhSo.setBackground(new Color(30, 30, 80));
            btnDoanhSo.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_btnDoanhSoMouseEntered

    private void btnDoanhSoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoanhSoMouseExited
        if (btnDoanhSo != currentSelectedLabel) {
            btnDoanhSo.setOpaque(false); // Trả về trong suốt
            btnDoanhSo.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_btnDoanhSoMouseExited

    private void btnThongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongkeMouseEntered
        if (btnThongke != currentSelectedLabel) {
            btnThongke.setOpaque(true);
            btnThongke.setBackground(new Color(30, 30, 80));
            btnThongke.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_btnThongkeMouseEntered

    private void btnThongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongkeMouseExited
        if (btnThongke != currentSelectedLabel) {
            btnThongke.setOpaque(false); // Trả về trong suốt
            btnThongke.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_btnThongkeMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        if (btnLogout != currentSelectedLabel) {
            btnLogout.setOpaque(true);
            btnLogout.setBackground(new Color(30, 30, 80));
            btnLogout.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        if (btnLogout != currentSelectedLabel) {
            btnLogout.setOpaque(false); // Trả về trong suốt
            btnLogout.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnTrangchuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangchuMouseClicked
        showPanel(new panelTrangchu()); // Ví dụ chuyển cảnh

        // Đánh dấu nút này là nút đang chọn
        currentSelectedLabel = btnTrangchu;

        // Gọi hàm reset để tô màu cam cho nút này và xám cho nút khác
        resetMenuButtons(btnTrangchu);
    }//GEN-LAST:event_btnTrangchuMouseClicked

    private void btnBanhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanhangMouseClicked
        showPanel(new panelBanhang()); // Đảm bảo tên class Panel này đúng
        currentSelectedLabel = btnBanhang;
        resetMenuButtons(btnBanhang);
    }//GEN-LAST:event_btnBanhangMouseClicked

    private void btnSanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanphamMouseClicked
        showPanel(new panelSanpham()); // Đảm bảo tên class Panel này đúng
        currentSelectedLabel = btnSanpham;
        resetMenuButtons(btnSanpham);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSanphamMouseClicked

    private void btnHoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoadonMouseClicked
        showPanel(new panelHoadon()); // Đảm bảo tên class Panel này đúng
        currentSelectedLabel = btnHoadon;
        resetMenuButtons(btnHoadon);
    }//GEN-LAST:event_btnHoadonMouseClicked

    private void btnKhuyenmaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhuyenmaiMouseClicked
        showPanel(new panelKhuyenmai()); // Đảm bảo tên class Panel này đúng
        currentSelectedLabel = btnKhuyenmai;
        resetMenuButtons(btnKhuyenmai);
    }//GEN-LAST:event_btnKhuyenmaiMouseClicked

    private void btnTaikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaikhoanMouseClicked
        showPanel(new panelTaikhoan());
        currentSelectedLabel = btnTaikhoan;
        resetMenuButtons(btnTaikhoan);
    }//GEN-LAST:event_btnTaikhoanMouseClicked

    private void btnDoanhSoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoanhSoMouseClicked
        showPanel(new panelGiaodich());
        currentSelectedLabel = btnDoanhSo;
        resetMenuButtons(btnDoanhSo);
    }//GEN-LAST:event_btnDoanhSoMouseClicked

    private void btnThongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongkeMouseClicked
        showPanel(new panelThongke());
        currentSelectedLabel = btnThongke;
        resetMenuButtons(btnThongke);
    }//GEN-LAST:event_btnThongkeMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        currentSelectedLabel = btnLogout;
        resetMenuButtons(btnLogout);
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnRoleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRoleMouseClicked
        showPanel(new panelRolePermission());
        currentSelectedLabel = btnRole;
        resetMenuButtons(btnRole);
    }//GEN-LAST:event_btnRoleMouseClicked

    private void btnRoleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRoleMouseEntered
        if (btnRole != currentSelectedLabel) {
            btnRole.setOpaque(true);
            btnRole.setBackground(new Color(30, 30, 80));
            btnRole.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_btnRoleMouseEntered

    private void btnRoleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRoleMouseExited
        if (btnRole != currentSelectedLabel) {
            btnRole.setOpaque(false); // Trả về trong suốt
            btnRole.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_btnRoleMouseExited
    private boolean isTrangChuExpanded = false;
    private void btnArrowTrangchuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArrowTrangchuMouseClicked
        isTrangChuExpanded = !isTrangChuExpanded; // Đảo trạng thái

        btnDoanhSo.setVisible(isTrangChuExpanded);
        btnThongke.setVisible(isTrangChuExpanded);

        if (isTrangChuExpanded) {
            btnArrowTrangchu.setText("▲");
        } else {
            btnArrowTrangchu.setText("▼");
        }

        Menu.revalidate();
        Menu.repaint();
    }//GEN-LAST:event_btnArrowTrangchuMouseClicked

    private void btnArrowTrangchuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArrowTrangchuMouseEntered
        btnTrangchuMouseEntered(evt);
    }//GEN-LAST:event_btnArrowTrangchuMouseEntered

    private void btnArrowTrangchuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArrowTrangchuMouseExited
        btnTrangchuMouseExited(evt);
    }//GEN-LAST:event_btnArrowTrangchuMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.setProperty("awt.useSystemAAFontSettings", "on");
        System.setProperty("swing.aatext", "true");
        try {
            javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());

            javax.swing.UIManager.put("defaultFont", new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 13));
        } catch (Exception ex) {
            System.err.println("Không thể khởi tạo FlatLaf");
        }

        // 2. Code gọi cửa sổ AdminForm hiện lên (Giữ nguyên code cũ của bạn ở phần này)
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Layout;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel RoleName;
    private javax.swing.JLabel Title2;
    private javax.swing.JLabel btnArrowTrangchu;
    private javax.swing.JLabel btnBanhang;
    private javax.swing.JLabel btnDoanhSo;
    private javax.swing.JLabel btnHoadon;
    private javax.swing.JLabel btnKhuyenmai;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnRole;
    private javax.swing.JLabel btnSanpham;
    private javax.swing.JLabel btnTaikhoan;
    private javax.swing.JLabel btnThongke;
    private javax.swing.JLabel btnTrangchu;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelView;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
