/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.AdminPortalPanel.DashBoardPnl;
import View.AdminPortalPanel.RolePnl;

/**
 *
 * @author HUY0406
 */
public class AdminPortal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminPortal.class.getName());

    /**
     * Creates new form AdminPortal
     */
    public AdminPortal() {
        initComponents();
        this.setSize(1100, 650);
        this.setResizable(true);
        this.setLocationRelativeTo(null);
    }

    private void showPanel(javax.swing.JPanel panel) {
        pnlRightWorkspace.removeAll();
        pnlRightWorkspace.add(panel);
        pnlRightWorkspace.revalidate();
        pnlRightWorkspace.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlSideBar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnDashboard = new Custom_Component.MyButton();
        btnDashboard1 = new Custom_Component.MyButton();
        btnDashboard4 = new Custom_Component.MyButton();
        btnDashboard5 = new Custom_Component.MyButton();
        btnDashboard6 = new Custom_Component.MyButton();
        btnDashboard7 = new Custom_Component.MyButton();
        pnlRightWorkspace = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        pnlAccountList = new Custom_Component.RoundPanel();
        pnlAssignRole = new Custom_Component.RoundPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSideBar.setBackground(new java.awt.Color(30, 41, 59));
        pnlSideBar.setPreferredSize(new java.awt.Dimension(220, 250));
        pnlSideBar.setLayout(new javax.swing.BoxLayout(pnlSideBar, javax.swing.BoxLayout.Y_AXIS));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Admin Portal");
        pnlSideBar.add(jLabel3);

        btnDashboard.setBackground(new java.awt.Color(30, 41, 59));
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("DashBoard");
        btnDashboard.setBorderPainted(false);
        btnDashboard.setColorClick(new java.awt.Color(37, 99, 235));
        btnDashboard.setColorHover(new java.awt.Color(71, 85, 105));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnDashboard.setMaximumSize(new java.awt.Dimension(200, 50));
        btnDashboard.setPreferredSize(new java.awt.Dimension(200, 50));
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
        });
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);
        pnlSideBar.add(btnDashboard);

        btnDashboard1.setBackground(new java.awt.Color(30, 41, 59));
        btnDashboard1.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard1.setText("Account Management");
        btnDashboard1.setBorderPainted(false);
        btnDashboard1.setColorClick(new java.awt.Color(37, 99, 235));
        btnDashboard1.setColorHover(new java.awt.Color(71, 85, 105));
        btnDashboard1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDashboard1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard1.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnDashboard1.setMaximumSize(new java.awt.Dimension(200, 50));
        btnDashboard1.setPreferredSize(new java.awt.Dimension(200, 50));
        btnDashboard1.addActionListener(this::btnDashboard1ActionPerformed);
        pnlSideBar.add(btnDashboard1);

        btnDashboard4.setBackground(new java.awt.Color(30, 41, 59));
        btnDashboard4.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard4.setText("Role & Permission");
        btnDashboard4.setBorderPainted(false);
        btnDashboard4.setColorClick(new java.awt.Color(37, 99, 235));
        btnDashboard4.setColorHover(new java.awt.Color(71, 85, 105));
        btnDashboard4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDashboard4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard4.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnDashboard4.setMaximumSize(new java.awt.Dimension(200, 50));
        btnDashboard4.setPreferredSize(new java.awt.Dimension(200, 50));
        btnDashboard4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboard4MouseClicked(evt);
            }
        });
        btnDashboard4.addActionListener(this::btnDashboard4ActionPerformed);
        pnlSideBar.add(btnDashboard4);

        btnDashboard5.setBackground(new java.awt.Color(30, 41, 59));
        btnDashboard5.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard5.setText("Audit Logs");
        btnDashboard5.setBorderPainted(false);
        btnDashboard5.setColorClick(new java.awt.Color(37, 99, 235));
        btnDashboard5.setColorHover(new java.awt.Color(71, 85, 105));
        btnDashboard5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDashboard5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard5.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnDashboard5.setMaximumSize(new java.awt.Dimension(200, 50));
        btnDashboard5.setPreferredSize(new java.awt.Dimension(200, 50));
        btnDashboard5.addActionListener(this::btnDashboard5ActionPerformed);
        pnlSideBar.add(btnDashboard5);

        btnDashboard6.setBackground(new java.awt.Color(30, 41, 59));
        btnDashboard6.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard6.setText("Settings");
        btnDashboard6.setBorderPainted(false);
        btnDashboard6.setColorClick(new java.awt.Color(37, 99, 235));
        btnDashboard6.setColorHover(new java.awt.Color(71, 85, 105));
        btnDashboard6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDashboard6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard6.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnDashboard6.setMaximumSize(new java.awt.Dimension(200, 50));
        btnDashboard6.setPreferredSize(new java.awt.Dimension(200, 50));
        btnDashboard6.addActionListener(this::btnDashboard6ActionPerformed);
        pnlSideBar.add(btnDashboard6);

        btnDashboard7.setBackground(new java.awt.Color(30, 41, 59));
        btnDashboard7.setForeground(new java.awt.Color(255, 0, 0));
        btnDashboard7.setText("Log out");
        btnDashboard7.setBorderPainted(false);
        btnDashboard7.setColorClick(new java.awt.Color(37, 99, 235));
        btnDashboard7.setColorHover(new java.awt.Color(71, 85, 105));
        btnDashboard7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDashboard7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard7.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnDashboard7.setMaximumSize(new java.awt.Dimension(200, 50));
        btnDashboard7.setPreferredSize(new java.awt.Dimension(200, 50));
        btnDashboard7.addActionListener(this::btnDashboard7ActionPerformed);
        pnlSideBar.add(btnDashboard7);

        getContentPane().add(pnlSideBar, java.awt.BorderLayout.WEST);

        pnlRightWorkspace.setBackground(new java.awt.Color(240, 240, 240));
        pnlRightWorkspace.setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(241, 245, 249));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1000, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Account Assign Role");

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Assign or update role permissions for user accounts");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2)))
                .addContainerGap(614, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlRightWorkspace.add(pnlHeader, java.awt.BorderLayout.NORTH);

        pnlContent.setBackground(new java.awt.Color(241, 245, 249));
        pnlContent.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        pnlContent.setLayout(new java.awt.GridBagLayout());

        pnlAccountList.setBackground(new java.awt.Color(255, 255, 255));
        pnlAccountList.setPreferredSize(new java.awt.Dimension(670, 571));

        javax.swing.GroupLayout pnlAccountListLayout = new javax.swing.GroupLayout(pnlAccountList);
        pnlAccountList.setLayout(pnlAccountListLayout);
        pnlAccountListLayout.setHorizontalGroup(
            pnlAccountListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );
        pnlAccountListLayout.setVerticalGroup(
            pnlAccountListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.65;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        pnlContent.add(pnlAccountList, gridBagConstraints);

        pnlAssignRole.setBackground(new java.awt.Color(255, 255, 255));
        pnlAssignRole.setPreferredSize(new java.awt.Dimension(300, 0));

        javax.swing.GroupLayout pnlAssignRoleLayout = new javax.swing.GroupLayout(pnlAssignRole);
        pnlAssignRole.setLayout(pnlAssignRoleLayout);
        pnlAssignRoleLayout.setHorizontalGroup(
            pnlAssignRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlAssignRoleLayout.setVerticalGroup(
            pnlAssignRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.35;
        gridBagConstraints.weighty = 1.0;
        pnlContent.add(pnlAssignRole, gridBagConstraints);

        pnlRightWorkspace.add(pnlContent, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlRightWorkspace, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        showPanel(new DashBoardPnl());
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnDashboard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboard1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboard1ActionPerformed

    private void btnDashboard4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboard4ActionPerformed
        showPanel(new RolePnl());
    }//GEN-LAST:event_btnDashboard4ActionPerformed

    private void btnDashboard5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboard5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboard5ActionPerformed

    private void btnDashboard6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboard6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboard6ActionPerformed

    private void btnDashboard4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboard4MouseClicked

    }//GEN-LAST:event_btnDashboard4MouseClicked

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnDashboard7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboard7ActionPerformed
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDashboard7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminPortal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom_Component.MyButton btnDashboard;
    private Custom_Component.MyButton btnDashboard1;
    private Custom_Component.MyButton btnDashboard4;
    private Custom_Component.MyButton btnDashboard5;
    private Custom_Component.MyButton btnDashboard6;
    private Custom_Component.MyButton btnDashboard7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private Custom_Component.RoundPanel pnlAccountList;
    private Custom_Component.RoundPanel pnlAssignRole;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlRightWorkspace;
    private javax.swing.JPanel pnlSideBar;
    // End of variables declaration//GEN-END:variables
}
