/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Business.Main.LoginProcess;
import Common.Util.HashUtil;
import Model.Account;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author HUY0406
 */
public class LoginUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginUI.class.getName());

    /**
     * Creates new form LoginUI
     */
    public LoginUI() {

        initComponents();

// --- BƯỚC 1: ĐỔI MÀU KHU VỰC MÀU XÁM THÀNH GRADIENT ---
        // Chúng ta không dùng setContentPane nữa để tránh đè mất components
        // Thay vào đó, ta vẽ trực tiếp lên lớp nền của JFrame
        JPanel mainContent = (JPanel) this.getContentPane();
        mainContent.setOpaque(false); // Làm lớp nội dung mặc định trong suốt

        // Tạo một Panel mới để vẽ màu nền Gradient
        javax.swing.JPanel backgroundLayer = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;
                java.awt.GradientPaint gp = new java.awt.GradientPaint(
                        0, 0, new java.awt.Color(255, 218, 185), // Cam đào (Top)
                        0, getHeight(), new java.awt.Color(255, 182, 193) // Hồng nhạt (Bottom)
                );
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, getWidth(), getHeight());
            }
        };

        // Đặt backgroundLayer này xuống dưới cùng
        this.setContentPane(backgroundLayer);
        backgroundLayer.setLayout(new java.awt.GridBagLayout()); // GridBagLayout giúp khung trắng tự động căn giữa

        // --- BƯỚC 2: ĐƯA JPANEL1 (KHUNG TRẮNG) VÀO NỀN MỚI ---
        // Giả sử cái khung trắng của bạn tên là jPanel1
        if (jPanel1 != null) {
            backgroundLayer.add(jPanel1);
        }

        // Cấu hình JFrame của bạn
        this.setSize(1200, 800);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;
                g2d.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Đặt màu cho Panel (có thể dùng Gradient ở đây)
                g2d.setColor(getBackground());

                // Vẽ hình chữ nhật bo tròn: x, y, width, height, arcWidth, arcHeight
                g2d.fillRoundRect(0, 0, getWidth(), getHeight(), 50, 50);
            }

            @Override
            public void setOpaque(boolean isOpaque) {
                super.setOpaque(false); // Ép panel luôn không trong suốt để thấy góc bo
            }
        };
        jPanel3 = new javax.swing.JPanel();
        DangNhap = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel(){
            {
                // Quan trọng: Phải để trong suốt để thấy được bo góc trên nền cha
                setOpaque(false);
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2d = (java.awt.Graphics2D) g.create(); // Dùng .create() để giữ an toàn cho Graphics gốc

                // --- Bật các chế độ làm nét và chống răng cưa cho đường cong ---
                g2d.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2d.setRenderingHint(java.awt.RenderingHints.KEY_INTERPOLATION, java.awt.RenderingHints.VALUE_INTERPOLATION_BILINEAR);
                g2d.setRenderingHint(java.awt.RenderingHints.KEY_RENDERING, java.awt.RenderingHints.VALUE_RENDER_QUALITY);

                int width = getWidth();
                int height = getHeight();
                int arc = 30; // Độ bo góc (chỉnh số này càng lớn góc càng tròn)

                // --- Tạo khuôn cắt bo góc (Clipping) ---
                // Sử dụng Shape để cắt ảnh theo hình chữ nhật bo góc
                java.awt.geom.RoundRectangle2D roundRect = new java.awt.geom.RoundRectangle2D.Float(0, 0, width, height, arc, arc);
                g2d.setClip(roundRect);

                java.net.URL imgURL = getClass().getResource("/Resource/backgroundLogin1.png");
                if (imgURL != null) {
                    javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
                    // Vẽ ảnh vào trong khuôn đã cắt
                    g2d.drawImage(icon.getImage(), 0, 0, width, height, this);
                } else {
                    g2d.setColor(new java.awt.Color(10, 50, 120));
                    g2d.fillRoundRect(0, 0, width, height, arc, arc);
                }

                g2d.dispose(); // Giải phóng tài nguyên đồ họa
            }
        };
        inform1 = new javax.swing.JLabel();
        matKhau = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        dangNhap = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        checkGhiNho = new javax.swing.JCheckBox();
        forgotPassText = new javax.swing.JLabel();
        loginBtn = new View.CustomComponents.RoundedButton("ĐĂNG NHẬP", 20);
        jLabel6 = new javax.swing.JLabel();
        SignUpText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        DangNhap.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        DangNhap.setText("ĐĂNG NHẬP");

        jPanel2.setBackground(new java.awt.Color(255, 0, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        inform1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inform1.setForeground(new java.awt.Color(153, 153, 153));
        inform1.setText("Vui lòng đăng nhập thông tin tài khoản của bạn");

        matKhau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        matKhau.setText("Mật khẩu");

        usernameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameField.setForeground(new java.awt.Color(51, 51, 51));
        usernameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        usernameField.setSelectionColor(new java.awt.Color(204, 229, 255));
        usernameField.addActionListener(this::usernameFieldActionPerformed);

        dangNhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dangNhap.setText("Tên đăng nhập");

        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordField.setForeground(new java.awt.Color(51, 51, 51));
        passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        passwordField.setSelectionColor(new java.awt.Color(204, 229, 255));

        checkGhiNho.setText("Ghi nhớ đăng nhập");

        forgotPassText.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        forgotPassText.setForeground(new java.awt.Color(0, 0, 255));
        forgotPassText.setText("Quên mật khẩu");
        forgotPassText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPassTextMouseClicked(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(0, 0, 204));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("ĐĂNG NHẬP");
        loginBtn.addActionListener(this::loginBtnActionPerformed);

        jLabel6.setText("Chưa có tài khoản?");

        SignUpText.setForeground(new java.awt.Color(0, 0, 255));
        SignUpText.setText("Đăng ký ngay");
        SignUpText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpTextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(151, 151, 151))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(inform1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usernameField)
                                    .addComponent(dangNhap)
                                    .addComponent(matKhau)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(checkGhiNho)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                                        .addComponent(forgotPassText))
                                    .addComponent(passwordField)
                                    .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SignUpText, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(DangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inform1)
                .addGap(51, 51, 51)
                .addComponent(dangNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(matKhau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkGhiNho)
                    .addComponent(forgotPassText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(SignUpText))
                .addGap(231, 231, 231))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null); // Đưa ra giữa
        this.getContentPane().setBackground(new java.awt.Color(240, 240, 240)); // Đổi màu nền
    }//GEN-LAST:event_formWindowOpened

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed

        String username = usernameField.getText();
        String password = passwordField.getText();

        String passwordHash = HashUtil.hashPassword(password);
        LoginProcess loginProcess = new LoginProcess();

        Account acc = loginProcess.executeLogin(username, passwordHash);

        if (acc != null) {
            JOptionPane optionPane = new JOptionPane("Đăng nhập thành công", JOptionPane.INFORMATION_MESSAGE);
            JDialog dialog = optionPane.createDialog("Thành công");
            dialog.setAlwaysOnTop(true);
            dialog.setVisible(true);

        } else {
            JOptionPane optionPane = new JOptionPane("Đăng nhập thất bại", JOptionPane.ERROR_MESSAGE);
            JDialog dialog = optionPane.createDialog("Thất Bại");
            dialog.setAlwaysOnTop(true);
            dialog.setVisible(true);
        }
    }

    private void codeloi(java.awt.event.ActionEvent evt) {
    }//GEN-LAST:event_loginBtnActionPerformed

    private void forgotPassTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPassTextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_forgotPassTextMouseClicked

    private void SignUpTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpTextMouseClicked
        RegisterUI register = new RegisterUI();
        register.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        register.setVisible(true);
        register.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_SignUpTextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DangNhap;
    private javax.swing.JLabel SignUpText;
    private javax.swing.JCheckBox checkGhiNho;
    private javax.swing.JLabel dangNhap;
    private javax.swing.JLabel forgotPassText;
    private javax.swing.JLabel inform1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel matKhau;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
