/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Business.Main.RegisterProcess;
import Common.Util.HashUtil;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author HUY0406
 */
public class RegisterForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterForm.class.getName());

    /**
     * Creates new form LoginForm
     */
    public RegisterForm() {
        initComponents();
        initComboBoxData();
        this.setSize(1100, 650);
        this.setResizable(true);
        this.setLocationRelativeTo(null);
        // 1. Lấy lại Panel gốc chứa giao diện do NetBeans tự sinh
        java.awt.Container oldContentPane = this.getContentPane();
        if (oldContentPane instanceof javax.swing.JPanel) {
            // Làm cho Panel gốc trong suốt để nhìn xuyên thấu xuống dưới
            ((javax.swing.JPanel) oldContentPane).setOpaque(false);
        }

        // 2. Tạo một Panel mới để vẽ màu nền Gradient (dùng BorderLayout để chứa mâm cũ vừa khít)
        javax.swing.JPanel backgroundLayer = new javax.swing.JPanel(new java.awt.BorderLayout()) {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;
                // Cam đào (Top) xuống Hồng nhạt (Bottom)
                java.awt.GradientPaint gp = new java.awt.GradientPaint(
                        0, 0, new java.awt.Color(255, 218, 185),
                        0, getHeight(), new java.awt.Color(255, 182, 193)
                );
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, getWidth(), getHeight());
            }
        };

        // 3. Đặt toàn bộ giao diện cũ vào đè lên trên cái nền Gradient
        backgroundLayer.add(oldContentPane);

        // 4. Set lại Content Pane mới
        this.setContentPane(backgroundLayer);
    }

    private void initComboBoxData() {
        // 1. Thêm số cho Ngày (từ 1 đến 31)
        cboNgay.removeAllItems(); // Xóa dữ liệu cũ (nếu có)
        for (int i = 1; i <= 31; i++) {
            cboNgay.addItem(String.valueOf(i));
        }

        // 2. Thêm số cho Tháng (từ 1 đến 12)
        cboThang.removeAllItems();
        for (int i = 1; i <= 12; i++) {
            cboThang.addItem(String.valueOf(i));
        }

        // 3. Thêm số cho Năm (Lấy từ năm hiện tại lùi về năm 1900)
        cboNam.removeAllItems();
        int currentYear = java.time.Year.now().getValue(); // Tự động lấy năm hiện tại (VD: 2026)
        for (int i = currentYear; i >= 1900; i--) {
            cboNam.addItem(String.valueOf(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        roundPanel1 = new Custom_Component.RoundPanel();
        imagePanel2 = new Custom_Component.ImagePanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userNameField = new Custom_Component.MyTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordField = new Custom_Component.MyPasswordField();
        btnSignUp = new Custom_Component.MyButton();
        signInText = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameField = new Custom_Component.MyTextField();
        jLabel8 = new javax.swing.JLabel();
        phoneNumberField = new Custom_Component.MyTextField();
        jLabel5 = new javax.swing.JLabel();
        password2Field = new Custom_Component.MyPasswordField();
        jLabel9 = new javax.swing.JLabel();
        cboNam = new Custom_Component.MyComboBox();
        cboNgay = new Custom_Component.MyComboBox();
        cboThang = new Custom_Component.MyComboBox();
        rbNu = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        rbNam = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel1.setPreferredSize(new java.awt.Dimension(1000, 580));
        roundPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagePanel2.setImage(new javax.swing.ImageIcon(getClass().getResource("/Resource/backgroundLogin3.png"))); // NOI18N
        imagePanel2.setPreferredSize(new java.awt.Dimension(460, 540));

        javax.swing.GroupLayout imagePanel2Layout = new javax.swing.GroupLayout(imagePanel2);
        imagePanel2.setLayout(imagePanel2Layout);
        imagePanel2Layout.setHorizontalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        imagePanel2Layout.setVerticalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        roundPanel1.add(imagePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" ĐĂNG KÝ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 40));
        roundPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("Mật khẩu");
        roundPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 400, 20));

        userNameField.setPreferredSize(new java.awt.Dimension(400, 40));
        roundPanel1.add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("Tên đăng nhập");
        roundPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 400, 21));

        passwordField.setPreferredSize(new java.awt.Dimension(400, 40));
        passwordField.addActionListener(this::passwordFieldActionPerformed);
        roundPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        btnSignUp.setBackground(new java.awt.Color(255, 107, 53));
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("ĐĂNG KÝ");
        btnSignUp.setColorClick(new java.awt.Color(227, 85, 32));
        btnSignUp.setColorHover(new java.awt.Color(255, 133, 86));
        btnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSignUp.setPreferredSize(new java.awt.Dimension(400, 45));
        btnSignUp.addActionListener(this::btnSignUpActionPerformed);
        roundPanel1.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 400, -1));

        signInText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signInText.setText("<html>Đã có tài khoản? <font color='#001CBA'><b>Đăng nhập ngay</b></font></html>");
        signInText.setPreferredSize(new java.awt.Dimension(400, 25));
        signInText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInTextMouseClicked(evt);
            }
        });
        roundPanel1.add(signInText, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setText("Họ và tên");
        roundPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 400, 20));

        nameField.setPreferredSize(new java.awt.Dimension(400, 40));
        roundPanel1.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setText("Giới tính");
        roundPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 90, 20));

        phoneNumberField.setPreferredSize(new java.awt.Dimension(400, 40));
        roundPanel1.add(phoneNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText("Nhập lại mật khẩu");
        roundPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 400, 20));

        password2Field.setPreferredSize(new java.awt.Dimension(400, 40));
        password2Field.addActionListener(this::password2FieldActionPerformed);
        roundPanel1.add(password2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setText("Số điện thoại");
        roundPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 400, 20));
        roundPanel1.add(cboNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, 110, 40));

        cboNgay.setToolTipText("");
        roundPanel1.add(cboNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 90, 40));
        cboNgay.getAccessibleContext().setAccessibleName("");

        roundPanel1.add(cboThang, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 90, 40));

        rbNu.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbNu);
        rbNu.setText("Nữ");
        rbNu.addActionListener(this::rbNuActionPerformed);
        roundPanel1.add(rbNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 60, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setText("Năm sinh");
        roundPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 90, 20));

        rbNam.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbNam);
        rbNam.setText("Nam");
        rbNam.addActionListener(this::rbNamActionPerformed);
        roundPanel1.add(rbNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 60, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel11.setText("Ngày sinh");
        roundPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 90, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel12.setText("Tháng sinh");
        roundPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 90, 20));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(roundPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed

        String name = nameField.getText();
        String user = userNameField.getText();
        String pass = passwordField.getText();
        String sdt = phoneNumberField.getText();

        String gioiTinh = "Nam";
        if (rbNu.isSelected()) {
            gioiTinh = "Nu";
        }

        String ngay = cboNgay.getSelectedItem().toString();
        String thang = cboThang.getSelectedItem().toString();
        String nam = cboNam.getSelectedItem().toString();

        if (name.isEmpty() || user.isEmpty() || pass.isEmpty() || sdt.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
            return;
        }

        String passwordHash = HashUtil.hashPassword(pass);

        RegisterProcess register_process = new RegisterProcess();
        boolean isSuccess = register_process.execute(name, sdt, gioiTinh, ngay, thang, nam, user, passwordHash);

        if (isSuccess) {
            javax.swing.JOptionPane.showMessageDialog(this, "Đăng ký tài khoản thành công!");

            LoginForm login = new LoginForm();
            login.setVisible(true);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Đăng ký thất bại! Số điện thoại/Email có thể đã tồn tại, hoặc do lỗi hệ thống.");
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void password2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password2FieldActionPerformed

    private void rbNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNuActionPerformed

    private void rbNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNamActionPerformed

    private void signInTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInTextMouseClicked
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signInTextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom_Component.MyButton btnSignUp;
    private javax.swing.ButtonGroup buttonGroup1;
    private Custom_Component.MyComboBox cboNam;
    private Custom_Component.MyComboBox cboNgay;
    private Custom_Component.MyComboBox cboThang;
    private Custom_Component.ImagePanel imagePanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private Custom_Component.MyTextField nameField;
    private Custom_Component.MyPasswordField password2Field;
    private Custom_Component.MyPasswordField passwordField;
    private Custom_Component.MyTextField phoneNumberField;
    private javax.swing.JRadioButton rbNam;
    private javax.swing.JRadioButton rbNu;
    private Custom_Component.RoundPanel roundPanel1;
    private javax.swing.JLabel signInText;
    private Custom_Component.MyTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
