/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Business.Main.LoginProcess;
import Business.Main.RegisterProcess;
import Common.Util.HashUtil;
import Model.Account;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author HUY0406
 */
public class RegisterUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterUI.class.getName());

    /**
     * Creates new form LoginUI
     */
    public RegisterUI() {

        initComponents();
        initDateCombo();

// --- BƯỚC 1: ĐỔI MÀU KHU VỰC MÀU XÁM THÀNH GRADIENT ---
        // Chúng ta không dùng setContentPane nữa để tránh đè mất components
        // Thay vào đó, ta vẽ trực tiếp lên lớp nền của JFrame
        JPanel mainContent = (JPanel) this.getContentPane();
        mainContent.setOpaque(false); // Làm lớp nội dung mặc định trong suốt

        // Tạo một Panel mới để vẽ màu nền Gradient
        javax.swing.JPanel backgroundLayer = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;
                java.awt.GradientPaint gp = new java.awt.GradientPaint(
                        0, 0, new java.awt.Color(255, 218, 185), // Cam đào (Top)
                        0, getHeight(), new java.awt.Color(255, 182, 193) // Hồng nhạt (Bottom)
                );
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, getWidth(), getHeight());
            }
        };

        // Đặt backgroundLayer này xuống dưới cùng
        this.setContentPane(backgroundLayer);
        backgroundLayer.setLayout(new java.awt.GridBagLayout()); // GridBagLayout giúp khung trắng tự động căn giữa

        // --- BƯỚC 2: ĐƯA JPANEL1 (KHUNG TRẮNG) VÀO NỀN MỚI ---
        // Giả sử cái khung trắng của bạn tên là jPanel1
        if (jPanel1 != null) {
            backgroundLayer.add(jPanel1);
        }

        // Cấu hình JFrame của bạn
        this.setSize(1200, 800);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;
                g2d.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Đặt màu cho Panel (có thể dùng Gradient ở đây)
                g2d.setColor(getBackground());

                // Vẽ hình chữ nhật bo tròn: x, y, width, height, arcWidth, arcHeight
                g2d.fillRoundRect(0, 0, getWidth(), getHeight(), 50, 50);
            }

            @Override
            public void setOpaque(boolean isOpaque) {
                super.setOpaque(false); // Ép panel luôn không trong suốt để thấy góc bo
            }
        };
        jPanel3 = new javax.swing.JPanel();
        DangNhap = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel(){
            {
                // Quan trọng: Phải để trong suốt để thấy được bo góc trên nền cha
                setOpaque(false);
            }

            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2d = (java.awt.Graphics2D) g.create(); // Dùng .create() để giữ an toàn cho Graphics gốc

                // --- Bật các chế độ làm nét và chống răng cưa cho đường cong ---
                g2d.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2d.setRenderingHint(java.awt.RenderingHints.KEY_INTERPOLATION, java.awt.RenderingHints.VALUE_INTERPOLATION_BILINEAR);
                g2d.setRenderingHint(java.awt.RenderingHints.KEY_RENDERING, java.awt.RenderingHints.VALUE_RENDER_QUALITY);

                int width = getWidth();
                int height = getHeight();
                int arc = 30; // Độ bo góc (chỉnh số này càng lớn góc càng tròn)

                // --- Tạo khuôn cắt bo góc (Clipping) ---
                // Sử dụng Shape để cắt ảnh theo hình chữ nhật bo góc
                java.awt.geom.RoundRectangle2D roundRect = new java.awt.geom.RoundRectangle2D.Float(0, 0, width, height, arc, arc);
                g2d.setClip(roundRect);

                java.net.URL imgURL = getClass().getResource("/Resource/backgroundLogin1.png");
                if (imgURL != null) {
                    javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
                    // Vẽ ảnh vào trong khuôn đã cắt
                    g2d.drawImage(icon.getImage(), 0, 0, width, height, this);
                } else {
                    g2d.setColor(new java.awt.Color(10, 50, 120));
                    g2d.fillRoundRect(0, 0, width, height, arc, arc);
                }

                g2d.dispose(); // Giải phóng tài nguyên đồ họa
            }
        };
        matKhau = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        dangNhap = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginBtn = new View.CustomComponents.RoundedButton("ĐĂNG NHẬP", 20);
        dangNhap1 = new javax.swing.JLabel();
        dangNhap2 = new javax.swing.JLabel();
        sdtField = new javax.swing.JTextField();
        cboNgay = new javax.swing.JComboBox<>();
        dangNhap3 = new javax.swing.JLabel();
        cboThang = new javax.swing.JComboBox<>();
        cboNam = new javax.swing.JComboBox<>();
        dangNhap4 = new javax.swing.JLabel();
        rbNam = new javax.swing.JRadioButton();
        rbNu = new javax.swing.JRadioButton();
        dangNhap7 = new javax.swing.JLabel();
        dangNhap5 = new javax.swing.JLabel();
        dangNhap6 = new javax.swing.JLabel();
        fullnameField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        DangNhap.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        DangNhap.setText("ĐĂNG KÝ");

        jPanel2.setBackground(new java.awt.Color(255, 0, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );

        matKhau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        matKhau.setText("Mật khẩu");

        usernameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameField.setForeground(new java.awt.Color(51, 51, 51));
        usernameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        usernameField.setSelectionColor(new java.awt.Color(204, 229, 255));
        usernameField.addActionListener(this::usernameFieldActionPerformed);

        dangNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dangNhap.setText("Tên đăng nhập");

        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordField.setForeground(new java.awt.Color(51, 51, 51));
        passwordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        passwordField.setSelectionColor(new java.awt.Color(204, 229, 255));

        loginBtn.setBackground(new java.awt.Color(0, 0, 204));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("ĐĂNG KÝ");
        loginBtn.addActionListener(this::loginBtnActionPerformed);

        dangNhap1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dangNhap1.setText("Họ và tên");

        dangNhap2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dangNhap2.setText("Nhập lại mật khẩu");

        sdtField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sdtField.setForeground(new java.awt.Color(51, 51, 51));
        sdtField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        sdtField.setSelectionColor(new java.awt.Color(204, 229, 255));
        sdtField.addActionListener(this::sdtFieldActionPerformed);

        cboNgay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày" }));
        cboNgay.addActionListener(this::cboNgayActionPerformed);

        dangNhap3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dangNhap3.setText("Ngày sinh");

        cboThang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng" }));

        cboNam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Năm" }));

        dangNhap4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dangNhap4.setText("Giới tính");

        buttonGroup1.add(rbNam);
        rbNam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbNam.setText("Nam");
        rbNam.addActionListener(this::rbNamActionPerformed);

        buttonGroup1.add(rbNu);
        rbNu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbNu.setText("Nữ");
        rbNu.addActionListener(this::rbNuActionPerformed);

        dangNhap7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dangNhap7.setText("SĐT");

        dangNhap5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dangNhap5.setText("Tháng sinh");

        dangNhap6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dangNhap6.setText("Năm sinh");

        fullnameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fullnameField.setForeground(new java.awt.Color(51, 51, 51));
        fullnameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        fullnameField.setSelectionColor(new java.awt.Color(204, 229, 255));
        fullnameField.addActionListener(this::fullnameFieldActionPerformed);

        EmailField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmailField.setForeground(new java.awt.Color(51, 51, 51));
        EmailField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        EmailField.setSelectionColor(new java.awt.Color(204, 229, 255));
        EmailField.addActionListener(this::EmailFieldActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dangNhap3)
                                    .addComponent(cboNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dangNhap5)
                                    .addComponent(cboThang, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dangNhap6)
                                    .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(dangNhap2)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dangNhap7)
                            .addComponent(dangNhap1)
                            .addComponent(fullnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dangNhap)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matKhau)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(EmailField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sdtField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
                            .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(dangNhap4)
                                .addGap(42, 42, 42)
                                .addComponent(rbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(rbNu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(DangNhap)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(DangNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dangNhap1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fullnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dangNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matKhau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dangNhap2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sdtField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(dangNhap7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dangNhap3)
                    .addComponent(dangNhap5)
                    .addComponent(dangNhap6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboThang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dangNhap4)
                    .addComponent(rbNam)
                    .addComponent(rbNu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null); // Đưa ra giữa
        this.getContentPane().setBackground(new java.awt.Color(240, 240, 240)); // Đổi màu nền
    }//GEN-LAST:event_formWindowOpened

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void fullnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameFieldActionPerformed

    private void rbNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNuActionPerformed

    private void rbNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNamActionPerformed

    private void cboNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNgayActionPerformed

    private void sdtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdtFieldActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // 1. Lấy dữ liệu từ các TextFields cũ của bạn
        String name = fullnameField.getText();
        String mail = EmailField.getText(); // Đây là trường Email của bạn
        String user = usernameField.getText();
        String pass = passwordField.getText();

        String sdt = sdtField.getText();

        String gioiTinh = "Nam"; // Mặc định hoặc xét điều kiện
        if (rbNu.isSelected()) {
            gioiTinh = "Nu";
        }

        String ngay = cboNgay.getSelectedItem().toString();
        String thang = cboThang.getSelectedItem().toString();
        String nam = cboNam.getSelectedItem().toString();

        // 3. Kiểm tra rỗng (Cập nhật thêm sdt)
        if (name.isEmpty() || mail.isEmpty() || user.isEmpty() || pass.isEmpty() || sdt.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
            return;
        }

        // 4. Mã hóa mật khẩu
        String passwordHash = HashUtil.hashPassword(pass);

        // 5. Gọi Process xử lý với ĐẦY ĐỦ 9 THAM SỐ mới
        RegisterProcess register_process = new RegisterProcess();
        boolean isSuccess = register_process.execute(name, sdt, gioiTinh, ngay, thang, nam, user, passwordHash);

        // 6. Xử lý kết quả trả về
        if (isSuccess) {
            javax.swing.JOptionPane.showMessageDialog(this, "Đăng ký tài khoản thành công!");

            LoginUI login = new LoginUI();
            login.setVisible(true);
            this.dispose(); // Đóng form đăng ký
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Đăng ký thất bại! Số điện thoại/Email có thể đã tồn tại, hoặc do lỗi hệ thống.");
        }
    }

    private void codeloi(java.awt.event.ActionEvent evt) {
    }//GEN-LAST:event_loginBtnActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void initDateCombo() {
        // Ngày
        cboNgay.removeAllItems();
        for (int i = 1; i <= 31; i++) {
            cboNgay.addItem(String.valueOf(i));
        }

        // Tháng
        cboThang.removeAllItems();
        for (int i = 1; i <= 12; i++) {
            cboThang.addItem(String.valueOf(i));
        }

        // Năm
        cboNam.removeAllItems();
        for (int i = 2026; i >= 1900; i--) {
            cboNam.addItem(String.valueOf(i));
        }

        // Giới tính mặc định chọn Nam
        rbNam.setSelected(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DangNhap;
    private javax.swing.JTextField EmailField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboNam;
    private javax.swing.JComboBox<String> cboNgay;
    private javax.swing.JComboBox<String> cboThang;
    private javax.swing.JLabel dangNhap;
    private javax.swing.JLabel dangNhap1;
    private javax.swing.JLabel dangNhap2;
    private javax.swing.JLabel dangNhap3;
    private javax.swing.JLabel dangNhap4;
    private javax.swing.JLabel dangNhap5;
    private javax.swing.JLabel dangNhap6;
    private javax.swing.JLabel dangNhap7;
    private javax.swing.JTextField fullnameField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel matKhau;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JRadioButton rbNam;
    private javax.swing.JRadioButton rbNu;
    private javax.swing.JTextField sdtField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
