--------------------------------------------------------------------------------
-- PHẦN 2: THIẾT LẬP RÀNG BUỘC KHÓA NGOẠI (FOREIGN KEYS)
-- Chú thích: Đảm bảo dữ liệu nhất quán giữa các bảng liên quan
--------------------------------------------------------------------------------

-- [1] CỤM QUẢN LÝ TÀI KHOẢN VÀ PHÂN QUYỀN
--------------------------------------------------------------------------------
-- Liên kết Tài khoản với thông tin Người dùng
ALTER TABLE ACCOUNT ADD CONSTRAINT FK_ACC_USER FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID);

-- Liên kết Quyền với Phân hệ chức năng
ALTER TABLE ROLE ADD CONSTRAINT FK_ROLE_FUNC FOREIGN KEY (FUNCTION_ID) REFERENCES FUNCTION(FUNCTION_ID);

-- Liên kết Nhóm quyền và Quyền (N-N)
ALTER TABLE ROLE_GROUP_ASSIGN_ROLE ADD CONSTRAINT FK_RGAR_RG FOREIGN KEY (ROLE_GROUP_ID) REFERENCES ROLE_GROUP(ROLE_GROUP_ID);
ALTER TABLE ROLE_GROUP_ASSIGN_ROLE ADD CONSTRAINT FK_RGAR_R FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID);

-- Gán Nhóm quyền cho Tài khoản (N-N)
ALTER TABLE ACCOUNT_ASSIGN_ROLE_GROUP ADD CONSTRAINT FK_AARG_ACC FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);
ALTER TABLE ACCOUNT_ASSIGN_ROLE_GROUP ADD CONSTRAINT FK_AARG_RG FOREIGN KEY (ROLE_GROUP_ID) REFERENCES ROLE_GROUP(ROLE_GROUP_ID);

-- Gán Quyền trực tiếp cho Tài khoản (N-N)
ALTER TABLE ACCOUNT_ASSIGN_ROLE ADD CONSTRAINT FK_AAR_ACC FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);
ALTER TABLE ACCOUNT_ASSIGN_ROLE ADD CONSTRAINT FK_AAR_R FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID);


-- [2] CỤM QUẢN LÝ SẢN PHẨM VÀ KHO HÀNG
--------------------------------------------------------------------------------
-- Sản phẩm thuộc về một Danh mục
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PROD_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID);

-- Danh mục cha - con (Tự tham chiếu)
ALTER TABLE CATEGORY ADD CONSTRAINT FK_CAT_PARENT FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID);

-- Quản lý Tồn kho: Sản phẩm trong các Kho hàng
ALTER TABLE INVENTORY ADD CONSTRAINT FK_INV_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);
ALTER TABLE INVENTORY ADD CONSTRAINT FK_INV_WH FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID);


-- [3] CỤM MARKETING - AFFILIATE - COUPON
--------------------------------------------------------------------------------
-- Affiliate là một Người dùng trong hệ thống
ALTER TABLE AFFILIATE ADD CONSTRAINT FK_AFF_USER FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID);

-- Coupon (Mã giảm giá) được sở hữu/giới thiệu bởi Affiliate
ALTER TABLE COUPON ADD CONSTRAINT FK_COUPON_AFF FOREIGN KEY (AFFILIATE_ID) REFERENCES AFFILIATE(AFFILIATE_ID);

-- Liên kết Sản phẩm vào Chiến dịch Khuyến mãi (N-N)
ALTER TABLE PROMOTION_PRODUCT ADD CONSTRAINT FK_PP_PROM FOREIGN KEY (PROMOTION_ID) REFERENCES PROMOTION(PROMOTION_ID);
ALTER TABLE PROMOTION_PRODUCT ADD CONSTRAINT FK_PP_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);


-- [4] CỤM QUẢN LÝ ĐƠN HÀNG VÀ THANH TOÁN
--------------------------------------------------------------------------------
-- Đơn hàng thuộc về một Người dùng và có thể áp dụng một Mã giảm giá
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORD_USER FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID);
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORD_COUP FOREIGN KEY (COUPON_ID) REFERENCES COUPON(COUPON_ID);

-- Chi tiết đơn hàng liên kết tới Đơn hàng tổng và Sản phẩm
ALTER TABLE ORDER_DETAIL ADD CONSTRAINT FK_OD_ORD FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID);
ALTER TABLE ORDER_DETAIL ADD CONSTRAINT FK_OD_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);

-- Thanh toán cho một Đơn hàng cụ thể
ALTER TABLE PAYMENT ADD CONSTRAINT FK_PAY_ORD FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID);


-- [5] CỤM CHĂM SÓC KHÁCH HÀNG (GIỎ HÀNG, ĐÁNH GIÁ, ĐIỂM THƯỞNG)
--------------------------------------------------------------------------------
-- Giỏ hàng và Điểm tích lũy của từng Người dùng
ALTER TABLE CART ADD CONSTRAINT FK_CART_USER FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID);
ALTER TABLE LOYALTY_POINT ADD CONSTRAINT FK_LOY_USER FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID);

-- Sản phẩm trong Giỏ hàng
ALTER TABLE CART_ITEM ADD CONSTRAINT FK_CI_CART FOREIGN KEY (CART_ID) REFERENCES CART(CART_ID);
ALTER TABLE CART_ITEM ADD CONSTRAINT FK_CI_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);

-- Người dùng đánh giá Sản phẩm
ALTER TABLE REVIEW ADD CONSTRAINT FK_REV_USER FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID);
ALTER TABLE REVIEW ADD CONSTRAINT FK_REV_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);


-- [6] CỤM MUA CHUNG (GROUP BUY)
--------------------------------------------------------------------------------
-- Nhóm mua chung cho một Sản phẩm cụ thể
ALTER TABLE GROUP_BUY ADD CONSTRAINT FK_GB_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);

-- Thành viên tham gia vào Nhóm mua chung
ALTER TABLE GROUP_BUY_PARTICIPANT ADD CONSTRAINT FK_GBP_GB FOREIGN KEY (GROUP_BUY_ID) REFERENCES GROUP_BUY(GROUP_BUY_ID);
ALTER TABLE GROUP_BUY_PARTICIPANT ADD CONSTRAINT FK_GBP_USER FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID);