-- Nhóm Người dùng & Quyền
ALTER TABLE ACCOUNT ADD CONSTRAINT FK_ACC_USER FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID);
ALTER TABLE ROLE ADD CONSTRAINT FK_ROLE_FUNC FOREIGN KEY (FUNCTION_ID) REFERENCES FUNCTION(FUNCTION_ID);
ALTER TABLE ROLE_GROUP_ASSIGN_ROLE ADD CONSTRAINT FK_RGA_RG FOREIGN KEY (ROLE_GROUP_ID) REFERENCES ROLE_GROUP(ROLE_GROUP_ID);
ALTER TABLE ROLE_GROUP_ASSIGN_ROLE ADD CONSTRAINT FK_RGA_R FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID);
ALTER TABLE ACCOUNT_ASSIGN_ROLE_GROUP ADD CONSTRAINT FK_AARG_ACC FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);
ALTER TABLE ACCOUNT_ASSIGN_ROLE_GROUP ADD CONSTRAINT FK_AARG_RG FOREIGN KEY (ROLE_GROUP_ID) REFERENCES ROLE_GROUP(ROLE_GROUP_ID);
ALTER TABLE ACCOUNT_ASSIGN_ROLE ADD CONSTRAINT FK_AAR_ACC FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);
ALTER TABLE ACCOUNT_ASSIGN_ROLE ADD CONSTRAINT FK_AAR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID);
ALTER TABLE ACCOUNT_TOKEN ADD CONSTRAINT FK_TOKEN_ACC FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);

-- Nhóm Sản phẩm & Kho
ALTER TABLE CATEGORY ADD CONSTRAINT FK_CAT_PARENT FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID);
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PROD_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID);
ALTER TABLE INVENTORY ADD CONSTRAINT FK_INV_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);
ALTER TABLE INVENTORY ADD CONSTRAINT FK_INV_WH FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID);
ALTER TABLE PROMOTION_PRODUCT ADD CONSTRAINT FK_PP_PROM FOREIGN KEY (PROMOTION_ID) REFERENCES PROMOTION(PROMOTION_ID);
ALTER TABLE PROMOTION_PRODUCT ADD CONSTRAINT FK_PP_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);

-- Nhóm Đơn hàng & Thanh toán
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORD_USER FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID);
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORD_COUPON FOREIGN KEY (COUPON_ID) REFERENCES COUPON(COUPON_ID);
ALTER TABLE ORDER_DETAIL ADD CONSTRAINT FK_DET_ORD FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID);
ALTER TABLE ORDER_DETAIL ADD CONSTRAINT FK_DET_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);
ALTER TABLE ORDER_DETAIL ADD CONSTRAINT FK_DET_WH FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID);
ALTER TABLE PAYMENT ADD CONSTRAINT FK_PAY_ORD FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID);

-- Nhóm Trải nghiệm & Mua chung
ALTER TABLE REVIEW ADD CONSTRAINT FK_REV_USER FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID);
ALTER TABLE REVIEW ADD CONSTRAINT FK_REV_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);
ALTER TABLE CART ADD CONSTRAINT FK_CART_USER FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID);
ALTER TABLE CART_ITEM ADD CONSTRAINT FK_ITEM_CART FOREIGN KEY (CART_ID) REFERENCES CART(CART_ID);
ALTER TABLE CART_ITEM ADD CONSTRAINT FK_ITEM_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);
ALTER TABLE LOYALTY_POINT ADD CONSTRAINT FK_LOY_USER FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID);
ALTER TABLE GROUP_BUY ADD CONSTRAINT FK_GB_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);
ALTER TABLE GROUP_BUY ADD CONSTRAINT FK_GB_HOST FOREIGN KEY (HOST_USER_ID) REFERENCES "USER"(USER_ID);
ALTER TABLE GROUP_BUY_PARTICIPANT ADD CONSTRAINT FK_GBP_GB FOREIGN KEY (GROUP_BUY_ID) REFERENCES GROUP_BUY(GROUP_BUY_ID);
ALTER TABLE GROUP_BUY_PARTICIPANT ADD CONSTRAINT FK_GBP_USER FOREIGN KEY (USER_ID) REFERENCES "USER"(USER_ID);
ALTER TABLE GROUP_BUY_PARTICIPANT ADD CONSTRAINT FK_GBP_ORD FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID);