/* ================= NHÓM BẢNG TÀI KHOẢN & PHÂN QUYỀN ================= */
CREATE OR REPLACE TRIGGER TRG_UPD_USERS_TIME
BEFORE UPDATE ON USERS FOR EACH ROW BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/
CREATE OR REPLACE TRIGGER TRG_UPD_ACCOUNT_TIME
BEFORE UPDATE ON ACCOUNT FOR EACH ROW BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/
CREATE OR REPLACE TRIGGER TRG_UPD_FUNCTIONS_TIME
BEFORE UPDATE ON FUNCTIONS FOR EACH ROW BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/
CREATE OR REPLACE TRIGGER TRG_UPD_ROLE_TIME
BEFORE UPDATE ON ROLE FOR EACH ROW BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/
CREATE OR REPLACE TRIGGER TRG_UPD_ROLE_GROUP_TIME
BEFORE UPDATE ON ROLE_GROUP FOR EACH ROW BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/
CREATE OR REPLACE TRIGGER TRG_UPD_RG_ASSIGN_ROLE_TIME
BEFORE UPDATE ON ROLE_GROUP_ASSIGN_ROLE FOR EACH ROW BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/
CREATE OR REPLACE TRIGGER TRG_UPD_ACC_ASSIGN_RG_TIME
BEFORE UPDATE ON ACCOUNT_ASSIGN_ROLE_GROUP FOR EACH ROW BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/
CREATE OR REPLACE TRIGGER TRG_UPD_ACC_ASSIGN_ROLE_TIME
BEFORE UPDATE ON ACCOUNT_ASSIGN_ROLE FOR EACH ROW BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/

/* ================= NHÓM BẢNG NGHIỆP VỤ & DÒNG TIỀN ================= */
CREATE OR REPLACE TRIGGER TRG_UPD_PRODUCT_TIME
BEFORE UPDATE ON PRODUCT FOR EACH ROW BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/
CREATE OR REPLACE TRIGGER TRG_UPD_INVENTORY_TIME
BEFORE UPDATE ON INVENTORY FOR EACH ROW BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/
CREATE OR REPLACE TRIGGER TRG_UPD_ORDERS_TIME
BEFORE UPDATE ON ORDERS FOR EACH ROW BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/
CREATE OR REPLACE TRIGGER TRG_UPD_PAYMENT_TIME
BEFORE UPDATE ON PAYMENT FOR EACH ROW BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/
CREATE OR REPLACE TRIGGER TRG_UPD_COUPON_TIME
BEFORE UPDATE ON COUPON FOR EACH ROW BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/
CREATE OR REPLACE TRIGGER TRG_UPD_PROMOTION_TIME
BEFORE UPDATE ON PROMOTION FOR EACH ROW BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/
CREATE OR REPLACE TRIGGER TRG_UPD_GROUP_BUY_TIME
BEFORE UPDATE ON GROUP_BUY FOR EACH ROW BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/

/* ================= NHÓM BẢNG KHÁCH HÀNG & HẬU MÃI ================= */
CREATE OR REPLACE TRIGGER TRG_UPD_CUSTOMER_TIME
BEFORE UPDATE ON CUSTOMER FOR EACH ROW BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/
CREATE OR REPLACE TRIGGER TRG_UPD_REVIEW_TIME
BEFORE UPDATE ON REVIEW FOR EACH ROW BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/
CREATE OR REPLACE TRIGGER TRG_UPD_WARRANTY_TIME
BEFORE UPDATE ON WARRANTY FOR EACH ROW BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/
CREATE OR REPLACE TRIGGER TRG_UPD_LOYALTY_POINT_TIME
BEFORE UPDATE ON LOYALTY_POINT FOR EACH ROW BEGIN :NEW.UPDATED_AT := SYSDATE; END;
/