-- 1. TRG_ORDER_TOTAL_CALC
CREATE OR REPLACE TRIGGER TRG_ORDER_TOTAL_CALC
AFTER INSERT OR UPDATE OR DELETE ON ORDER_DETAIL
FOR EACH ROW
DECLARE
    v_order_id NUMBER;
BEGIN
    IF INSERTING OR UPDATING THEN
        v_order_id := :NEW.ORDER_ID;
    ELSE
        v_order_id := :OLD.ORDER_ID;
    END IF;

    UPDATE ORDERS
    SET TOTAL = (
        SELECT NVL(SUM(QUANTITY * PRICE), 0)
        FROM ORDER_DETAIL
        WHERE ORDER_ID = v_order_id
    ) + NVL(SHIPPING_FEE,0),
    UPDATED_AT = SYSDATE
    WHERE ORDER_ID = v_order_id;
END;
/

-- 2. TRG_PAYMENT_SUCCESS_UPDATE_ORDER
CREATE OR REPLACE TRIGGER TRG_PAYMENT_SUCCESS_UPDATE_ORDER
AFTER UPDATE OF PAYMENT_STATUS ON PAYMENT
FOR EACH ROW
BEGIN
    IF :NEW.PAYMENT_STATUS = 'PAID' THEN
        UPDATE ORDERS
        SET STATUS = 'CONFIRMED',
            UPDATED_AT = SYSDATE
        WHERE ORDER_ID = :NEW.ORDER_ID;
    END IF;
END;
/

-- 3. TRG_CANCEL_ORDER_RESTORE_STOCK
CREATE OR REPLACE TRIGGER TRG_CANCEL_ORDER_RESTORE_STOCK
AFTER UPDATE OF STATUS ON ORDERS
FOR EACH ROW
BEGIN
    IF :NEW.STATUS = 'CANCELLED' AND :OLD.STATUS <> 'CANCELLED' THEN
        FOR r IN (
            SELECT PRODUCT_ID, WAREHOUSE_ID, QUANTITY
            FROM ORDER_DETAIL
            WHERE ORDER_ID = :NEW.ORDER_ID
        ) LOOP
            UPDATE INVENTORY
            SET QUANTITY = QUANTITY + r.QUANTITY,
                UPDATED_AT = SYSDATE
            WHERE PRODUCT_ID = r.PRODUCT_ID
              AND WAREHOUSE_ID = r.WAREHOUSE_ID;
        END LOOP;
    END IF;
END;
/

-- 4. TRG_CONFIRM_ORDER_DEDUCT_STOCK
CREATE OR REPLACE TRIGGER TRG_CONFIRM_ORDER_DEDUCT_STOCK
AFTER UPDATE OF STATUS ON ORDERS
FOR EACH ROW
BEGIN
    IF :NEW.STATUS = 'CONFIRMED' AND :OLD.STATUS <> 'CONFIRMED' THEN
        FOR r IN (
            SELECT PRODUCT_ID, WAREHOUSE_ID, QUANTITY
            FROM ORDER_DETAIL
            WHERE ORDER_ID = :NEW.ORDER_ID
        ) LOOP
            UPDATE INVENTORY
            SET QUANTITY = QUANTITY - r.QUANTITY,
                UPDATED_AT = SYSDATE
            WHERE PRODUCT_ID = r.PRODUCT_ID
              AND WAREHOUSE_ID = r.WAREHOUSE_ID;
        END LOOP;
    END IF;
END;
/

-- 5. TRG_PREVENT_ORDER_IF_OUT_OF_STOCK
CREATE OR REPLACE TRIGGER TRG_PREVENT_ORDER_IF_OUT_OF_STOCK
BEFORE INSERT ON ORDER_DETAIL
FOR EACH ROW
DECLARE
    v_qty NUMBER;
BEGIN
    SELECT QUANTITY INTO v_qty
    FROM INVENTORY
    WHERE PRODUCT_ID = :NEW.PRODUCT_ID
      AND WAREHOUSE_ID = :NEW.WAREHOUSE_ID;

    IF :NEW.QUANTITY > v_qty THEN
        RAISE_APPLICATION_ERROR(-20001, 'Khong du ton kho');
    END IF;
END;
/

-- 6. TRG_VALIDATE_COUPON_DATE
CREATE OR REPLACE TRIGGER TRG_VALIDATE_COUPON_DATE
BEFORE INSERT OR UPDATE ON ORDERS
FOR EACH ROW
DECLARE
    v_start DATE;
    v_end DATE;
BEGIN
    IF :NEW.COUPON_ID IS NOT NULL THEN
        SELECT START_AT, END_AT INTO v_start, v_end
        FROM COUPON
        WHERE COUPON_ID = :NEW.COUPON_ID;

        IF SYSDATE NOT BETWEEN v_start AND v_end THEN
            RAISE_APPLICATION_ERROR(-20002, 'Coupon het han hoac chua hieu luc');
        END IF;
    END IF;
END;
/

-- 7. TRG_DISABLE_EXPIRED_COUPON
CREATE OR REPLACE TRIGGER TRG_DISABLE_EXPIRED_COUPON
BEFORE UPDATE ON COUPON
FOR EACH ROW
BEGIN
    IF :NEW.END_AT < SYSDATE THEN
        :NEW.IS_ACTIVE := 0;
    END IF;
END;
/

-- 8. TRG_PREVENT_DUPLICATE_PROMOTION_PRODUCT
CREATE OR REPLACE TRIGGER TRG_PREVENT_DUPLICATE_PROMOTION_PRODUCT
BEFORE INSERT ON PROMOTION_PRODUCT
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM PROMOTION_PRODUCT
    WHERE PRODUCT_ID = :NEW.PRODUCT_ID;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'San pham da co khuyen mai');
    END IF;
END;
/

-- 9. TRG_GROUP_BUY_HOST_CONFIRM_SUCCESS
CREATE OR REPLACE TRIGGER TRG_GROUP_BUY_HOST_CONFIRM_SUCCESS
AFTER UPDATE OF STATUS ON GROUP_BUY
FOR EACH ROW
BEGIN
    IF :NEW.STATUS = 'SUCCESS'
       AND :OLD.STATUS <> 'SUCCESS' THEN
        IF :NEW.CURRENT_MEMBER < :NEW.TARGET_MEMBER THEN
            RAISE_APPLICATION_ERROR(-20012, 'Chua du thanh vien de xac nhan thanh cong');
        END IF;
    END IF;
END;
/

-- 10. TRG_GROUP_BUY_AUTO_FAIL
CREATE OR REPLACE TRIGGER TRG_GROUP_BUY_AUTO_FAIL
BEFORE UPDATE ON GROUP_BUY
FOR EACH ROW
BEGIN
    IF :NEW.EXPIRES_AT < SYSDATE
       AND :NEW.CURRENT_MEMBER < :NEW.TARGET_MEMBER THEN
        :NEW.STATUS := 'FAILED';
    END IF;
END;
/

-- 11. TRG_PREVENT_JOIN_EXPIRED_GROUP_BUY
CREATE OR REPLACE TRIGGER TRG_PREVENT_JOIN_EXPIRED_GROUP_BUY
BEFORE INSERT ON GROUP_BUY_PARTICIPANT
FOR EACH ROW
DECLARE
    v_exp DATE;
BEGIN
    SELECT EXPIRES_AT INTO v_exp
    FROM GROUP_BUY
    WHERE GROUP_BUY_ID = :NEW.GROUP_BUY_ID;

    IF v_exp < SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20004, 'Group buy da het han');
    END IF;
END;
/

-- 12. TRG_PREVENT_DUPLICATE_JOIN_GROUP_BUY
CREATE OR REPLACE TRIGGER TRG_PREVENT_DUPLICATE_JOIN_GROUP_BUY
BEFORE INSERT ON GROUP_BUY_PARTICIPANT
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM GROUP_BUY_PARTICIPANT
    WHERE GROUP_BUY_ID = :NEW.GROUP_BUY_ID
      AND USER_ID = :NEW.USER_ID;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20005, 'User da tham gia group buy');
    END IF;
END;
/

-- 13. TRG_REVIEW_ONLY_AFTER_PURCHASE
CREATE OR REPLACE TRIGGER TRG_REVIEW_ONLY_AFTER_PURCHASE
BEFORE INSERT ON REVIEW
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM ORDER_DETAIL od
    JOIN ORDERS o ON od.ORDER_ID = o.ORDER_ID
    WHERE o.USER_ID = :NEW.USER_ID
      AND od.PRODUCT_ID = :NEW.PRODUCT_ID;

    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20006, 'Chi nguoi da mua moi duoc review');
    END IF;
END;
/

-- 14. TRG_ADD_LOYALTY_POINTS_AFTER_DELIVERED
CREATE OR REPLACE TRIGGER TRG_ADD_LOYALTY_POINTS_AFTER_DELIVERED
AFTER UPDATE OF STATUS ON ORDERS
FOR EACH ROW
BEGIN
    IF :NEW.STATUS = 'DELIVERED' AND :OLD.STATUS <> 'DELIVERED' THEN
        UPDATE LOYALTY_POINT
        SET TOTAL_POINTS = TOTAL_POINTS + FLOOR(:NEW.TOTAL / 100000),
            UPDATED_AT = SYSDATE
        WHERE USER_ID = :NEW.USER_ID;
    END IF;
END;
/

-- 15. TRG_CART_QUANTITY_LIMIT
CREATE OR REPLACE TRIGGER TRG_CART_QUANTITY_LIMIT
BEFORE INSERT OR UPDATE ON CART_ITEM
FOR EACH ROW
DECLARE
    v_qty NUMBER;
BEGIN
    SELECT SUM(QUANTITY) INTO v_qty
    FROM INVENTORY
    WHERE PRODUCT_ID = :NEW.PRODUCT_ID;

    IF :NEW.QUANTITY > NVL(v_qty,0) THEN
        RAISE_APPLICATION_ERROR(-20007, 'Vuot qua ton kho');
    END IF;
END;
/

-- 16. TRG_PREVENT_DELETE_WAREHOUSE_IF_HAS_INVENTORY
CREATE OR REPLACE TRIGGER TRG_PREVENT_DELETE_WAREHOUSE_IF_HAS_INVENTORY
BEFORE UPDATE OF IS_DELETED ON WAREHOUSE
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM INVENTORY
    WHERE WAREHOUSE_ID = :NEW.WAREHOUSE_ID
      AND QUANTITY > 0;

    IF :NEW.IS_DELETED = 1 AND v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20008, 'Kho van con hang');
    END IF;
END;
/

-- 17. TRG_PREVENT_ORDER_IF_NO_RECEIVER_INFO
CREATE OR REPLACE TRIGGER TRG_PREVENT_ORDER_IF_NO_RECEIVER_INFO
BEFORE INSERT OR UPDATE ON ORDERS
FOR EACH ROW
BEGIN
    IF :NEW.RECEIVER_NAME IS NULL
       OR :NEW.RECEIVER_PHONE IS NULL
       OR :NEW.SHIPPING_ADDRESS IS NULL THEN
        RAISE_APPLICATION_ERROR(-20009, 'Thieu thong tin nguoi nhan');
    END IF;
END;
/

-- 18. TRG_LIMIT_GROUP_BUY_MEMBER
CREATE OR REPLACE TRIGGER TRG_LIMIT_GROUP_BUY_MEMBER
BEFORE INSERT ON GROUP_BUY_PARTICIPANT
FOR EACH ROW
DECLARE
    v_current NUMBER;
    v_target NUMBER;
BEGIN
    SELECT CURRENT_MEMBER, TARGET_MEMBER
    INTO v_current, v_target
    FROM GROUP_BUY
    WHERE GROUP_BUY_ID = :NEW.GROUP_BUY_ID;

    IF v_current >= v_target THEN
        RAISE_APPLICATION_ERROR(-20010, 'Group buy da du thanh vien');
    END IF;
END;
/

-- 19. TRG_PREVENT_PAYMENT_BEFORE_ORDER_DETAIL
CREATE OR REPLACE TRIGGER TRG_PREVENT_PAYMENT_BEFORE_ORDER_DETAIL
BEFORE INSERT ON PAYMENT
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM ORDER_DETAIL
    WHERE ORDER_ID = :NEW.ORDER_ID;

    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20011, 'Don hang chua co san pham');
    END IF;
END;
/

-- 20. TRG_AUTO_UPDATE_GROUP_BUY_MEMBER_COUNT
CREATE OR REPLACE TRIGGER TRG_AUTO_UPDATE_GROUP_BUY_MEMBER_COUNT
AFTER INSERT ON GROUP_BUY_PARTICIPANT
FOR EACH ROW
BEGIN
    UPDATE GROUP_BUY
    SET CURRENT_MEMBER = CURRENT_MEMBER + 1
    WHERE GROUP_BUY_ID = :NEW.GROUP_BUY_ID;
END;
/

-- 21. Trigger tự động xóa token hết hạn

CREATE OR REPLACE TRIGGER TRG_DELETE_EXPIRED_TOKEN
BEFORE INSERT OR UPDATE ON ACCOUNT_TOKEN
DECLARE
BEGIN
    DELETE FROM ACCOUNT_TOKEN
    WHERE EXPIRES_AT < SYSDATE
       OR IS_REVOKED = 'Y';
END;
/
