/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.User;

import Custom_Component.WrapLayout;
import DAO.ProductDAO;
import Model.ProductModel;
import Util.TokenMonitorManager;
import Util.UserSession;
import View.auth.LoginForm;
import View.panel.Customer.ProductCard;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author HUY0406
 */
public class CustomerForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerForm.class.getName());
    private int currentCategoryId = 0;

    private JLabel currentSelectedLabel = null;
    private final Color COLOR_NORMAL = Color.WHITE;
    private final Color COLOR_ACTIVE = new Color(255, 220, 185);

    /**
     * Creates new form CustomerForm
     */
    public CustomerForm() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        scrollPaneMain.getVerticalScrollBar().setUnitIncrement(20);
        scrollPaneMain.getHorizontalScrollBar().setUnitIncrement(20);

        loadDanhSachSanPham(0);
        startAutoRefresh(5);

    }

    public void loadDanhSachSanPham(int categoryId) {
        ProductDAO dao = new ProductDAO();
        List<ProductModel> dsSanPham;

        // 1. Kiểm tra tham số để quyết định lấy tất cả hay lọc theo danh mục
        if (categoryId == 0) {
            dsSanPham = dao.getAllProducts(); // Hàm lấy tất cả sản phẩm gốc của bạn
        } else {
            dsSanPham = dao.getProductsByCategory(categoryId); // Hàm lọc theo danh mục mới viết độc lập
        }

        // 2. Setup khung lưới tàng hình WrapLayout và dọn dẹp thẻ cũ
        pnlGrid.setLayout(new WrapLayout(FlowLayout.LEFT, 20, 20));
        pnlGrid.removeAll();

        // 3. Đúc thẻ, bơm dữ liệu và ném vào lưới
        for (ProductModel sp : dsSanPham) {
            ProductCard card = new ProductCard();

            // Gọi hàm setData để đổ tên, giá, ảnh và xử lý tag lửa tàng hình
            card.setData(sp);

            pnlGrid.add(card);
        }

        // 4. Ép giao diện load lại để hiển thị chính xác tăm tắp
        pnlGrid.revalidate();
        pnlGrid.repaint();
    }

    public void startAutoRefresh(int seconds) {
        // Đổi số giây nhập vào thành mili-giây (1 giây = 1000ms)
        int delay = seconds * 1000;

        Timer refreshTimer = new Timer(delay, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                loadDanhSachSanPham(0);
            }
        });
        refreshTimer.start();
    }

    public void setActiveCategoryLabel(JLabel clickedLabel) {
        if (currentSelectedLabel != null) {
            currentSelectedLabel.setBackground(COLOR_NORMAL);
        }
        currentSelectedLabel = clickedLabel;
        currentSelectedLabel.setOpaque(true);
        currentSelectedLabel.setBackground(COLOR_ACTIVE);

        currentSelectedLabel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMenuAvatar = new javax.swing.JPopupMenu();
        menuAccountInf = new javax.swing.JMenuItem();
        menuDonHang = new javax.swing.JMenuItem();
        menuLoyaltyPoint = new javax.swing.JMenuItem();
        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new Custom_Component.MyTextField();
        Cart = new Custom_Component.MyButton();
        MyAccount = new Custom_Component.MyButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSearch = new Custom_Component.MyButton();
        roundPanel2 = new Custom_Component.RoundPanel();
        lblSoLuongGioHang = new javax.swing.JLabel();
        BtnLogout = new Custom_Component.MyButton();
        scrollPaneMain = new javax.swing.JScrollPane();
        pnlWrapper = new javax.swing.JPanel();
        pnlBanner = new javax.swing.JPanel();
        roundPanel1 = new Custom_Component.RoundPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        myButton4 = new Custom_Component.MyButton();
        myButton5 = new Custom_Component.MyButton();
        imagePanel2 = new Custom_Component.ImagePanel();
        pnlProductGrid = new javax.swing.JPanel();
        pnlPolicies = new javax.swing.JPanel();
        pnlPolices1 = new Custom_Component.RoundPanel();
        roundPanel6 = new Custom_Component.RoundPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlPolicies2 = new Custom_Component.RoundPanel();
        roundPanel7 = new Custom_Component.RoundPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pnlPolicies3 = new Custom_Component.RoundPanel();
        roundPanel8 = new Custom_Component.RoundPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pnlPolicies5 = new Custom_Component.RoundPanel();
        roundPanel9 = new Custom_Component.RoundPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        pnlShopContent = new javax.swing.JPanel();
        pnlGrid = new javax.swing.JPanel();
        productCard1 = new View.panel.Customer.ProductCard();
        productCard2 = new View.panel.Customer.ProductCard();
        productCard3 = new View.panel.Customer.ProductCard();
        productCard4 = new View.panel.Customer.ProductCard();
        productCard5 = new View.panel.Customer.ProductCard();
        productCard6 = new View.panel.Customer.ProductCard();
        productCard7 = new View.panel.Customer.ProductCard();
        productCard8 = new View.panel.Customer.ProductCard();
        productCard9 = new View.panel.Customer.ProductCard();
        pnlCategory = new Custom_Component.RoundPanel();
        all = new Custom_Component.RoundPanel();
        AllCat = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Laptop = new Custom_Component.RoundPanel();
        LaptopCat = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        SmartPhone = new Custom_Component.RoundPanel();
        SmartPhoneCat = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        HeadPhone = new Custom_Component.RoundPanel();
        HeadphoneCat = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Screen = new Custom_Component.RoundPanel();
        ScreenCat = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        SmartWatch = new Custom_Component.RoundPanel();
        SmartWatchCat = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        GamingHand = new Custom_Component.RoundPanel();
        GamingCat = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        PhuKien = new Custom_Component.RoundPanel();
        PhuKienCat = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        DanhMucText = new javax.swing.JLabel();

        menuAccountInf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/8.png"))); // NOI18N
        menuAccountInf.setText("Thông tin tài khoản");
        menuAccountInf.addActionListener(this::menuAccountInfActionPerformed);
        popMenuAvatar.add(menuAccountInf);

        menuDonHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-cart-16.png"))); // NOI18N
        menuDonHang.setText("Đơn hàng của tôi");
        popMenuAvatar.add(menuDonHang);

        menuLoyaltyPoint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/7.png"))); // NOI18N
        menuLoyaltyPoint.setText("Đổi điểm thưởng");
        popMenuAvatar.add(menuLoyaltyPoint);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cửa Hàng Công Nghệ TechStore");

        pnlHeader.setBackground(new java.awt.Color(23, 37, 84));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1200, 75));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Smart");

        txtSearch.addActionListener(this::txtSearchActionPerformed);

        Cart.setBackground(new java.awt.Color(23, 37, 84));
        Cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-cart-48.png"))); // NOI18N
        Cart.setColorClick(new java.awt.Color(23, 37, 84));
        Cart.setColorHover(new java.awt.Color(23, 37, 84));
        Cart.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cart.addActionListener(this::CartActionPerformed);

        MyAccount.setBackground(new java.awt.Color(23, 37, 84));
        MyAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-user-32.png"))); // NOI18N
        MyAccount.setColorClick(new java.awt.Color(23, 37, 84));
        MyAccount.setColorHover(new java.awt.Color(23, 37, 84));
        MyAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyAccountMouseClicked(evt);
            }
        });
        MyAccount.addActionListener(this::MyAccountActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Giỏ hàng");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tài khoản");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hub");

        btnSearch.setBackground(new java.awt.Color(255, 102, 51));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-search-18 (1).png"))); // NOI18N

        roundPanel2.setBackground(new java.awt.Color(255, 102, 0));

        lblSoLuongGioHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSoLuongGioHang.setForeground(new java.awt.Color(255, 255, 255));
        lblSoLuongGioHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoLuongGioHang.setText("0");

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSoLuongGioHang, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSoLuongGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BtnLogout.setBackground(new java.awt.Color(231, 76, 60));
        BtnLogout.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-log-out-24.png"))); // NOI18N
        BtnLogout.setText("Đăng xuất");
        BtnLogout.setColorClick(new java.awt.Color(192, 57, 43));
        BtnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnLogout.addActionListener(this::BtnLogoutActionPerformed);

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MyAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cart, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(16, 16, 16))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(MyAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(Cart, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addContainerGap())))
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BtnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(pnlHeader, java.awt.BorderLayout.NORTH);

        scrollPaneMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrollPaneMain.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        pnlWrapper.setBackground(new java.awt.Color(255, 255, 255));
        pnlWrapper.setLayout(new java.awt.BorderLayout());

        pnlBanner.setBackground(new java.awt.Color(23, 37, 84));
        pnlBanner.setPreferredSize(new java.awt.Dimension(1500, 400));

        roundPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel5.setBackground(new java.awt.Color(255, 102, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-fire-16.png"))); // NOI18N
        jLabel5.setText("SALE ĐẾN 40%");

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Công nghệ đỉnh cao,");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Giá");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("CỰC HỢP LÝ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Khám phá hàng nghìn sản phẩm công nghệ chính hãng. ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Giao hàng nhanh, bảo hành uy tín, hỗ trợ 24/7");

        myButton4.setBackground(new java.awt.Color(255, 102, 0));
        myButton4.setForeground(new java.awt.Color(255, 255, 255));
        myButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-cart-26.png"))); // NOI18N
        myButton4.setText("Mua ngay");
        myButton4.setColorClick(new java.awt.Color(204, 82, 0));
        myButton4.setColorHover(new java.awt.Color(255, 128, 51));
        myButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        myButton5.setBackground(new java.awt.Color(51, 51, 255));
        myButton5.setForeground(new java.awt.Color(255, 255, 255));
        myButton5.setText("Xem khuyến mãi");
        myButton5.setColorClick(new java.awt.Color(0, 0, 204));
        myButton5.setColorHover(new java.awt.Color(102, 102, 255));
        myButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        imagePanel2.setImage(new javax.swing.ImageIcon(getClass().getResource("/Resource/BannerChinhThuc.png"))); // NOI18N

        javax.swing.GroupLayout imagePanel2Layout = new javax.swing.GroupLayout(imagePanel2);
        imagePanel2.setLayout(imagePanel2Layout);
        imagePanel2Layout.setHorizontalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        imagePanel2Layout.setVerticalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlBannerLayout = new javax.swing.GroupLayout(pnlBanner);
        pnlBanner.setLayout(pnlBannerLayout);
        pnlBannerLayout.setHorizontalGroup(
            pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBannerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBannerLayout.createSequentialGroup()
                        .addComponent(myButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(myButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addGroup(pnlBannerLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addComponent(jLabel6)
                    .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(imagePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        pnlBannerLayout.setVerticalGroup(
            pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBannerLayout.createSequentialGroup()
                .addGroup(pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBannerLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(myButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(myButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlBannerLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(imagePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnlWrapper.add(pnlBanner, java.awt.BorderLayout.NORTH);

        pnlProductGrid.setBackground(new java.awt.Color(245, 247, 250));

        pnlPolicies.setOpaque(false);
        pnlPolicies.setPreferredSize(new java.awt.Dimension(1494, 90));
        pnlPolicies.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        pnlPolices1.setBackground(new java.awt.Color(255, 255, 255));

        roundPanel6.setBackground(new java.awt.Color(255, 204, 153));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-shipping-32.png"))); // NOI18N

        javax.swing.GroupLayout roundPanel6Layout = new javax.swing.GroupLayout(roundPanel6);
        roundPanel6.setLayout(roundPanel6Layout);
        roundPanel6Layout.setHorizontalGroup(
            roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundPanel6Layout.setVerticalGroup(
            roundPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Giao hàng nhanh");

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Trong ngày tại TP.HCM & HN");

        javax.swing.GroupLayout pnlPolices1Layout = new javax.swing.GroupLayout(pnlPolices1);
        pnlPolices1.setLayout(pnlPolices1Layout);
        pnlPolices1Layout.setHorizontalGroup(
            pnlPolices1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPolices1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(roundPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPolices1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pnlPolices1Layout.setVerticalGroup(
            pnlPolices1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPolices1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlPolices1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPolices1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addComponent(roundPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlPolicies.add(pnlPolices1);

        pnlPolicies2.setBackground(new java.awt.Color(255, 255, 255));

        roundPanel7.setBackground(new java.awt.Color(255, 204, 153));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-shield-32.png"))); // NOI18N

        javax.swing.GroupLayout roundPanel7Layout = new javax.swing.GroupLayout(roundPanel7);
        roundPanel7.setLayout(roundPanel7Layout);
        roundPanel7Layout.setHorizontalGroup(
            roundPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundPanel7Layout.setVerticalGroup(
            roundPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Bảo hành chính hãng");

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("12-36 tháng tại hãng");

        javax.swing.GroupLayout pnlPolicies2Layout = new javax.swing.GroupLayout(pnlPolicies2);
        pnlPolicies2.setLayout(pnlPolicies2Layout);
        pnlPolicies2Layout.setHorizontalGroup(
            pnlPolicies2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPolicies2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(roundPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPolicies2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pnlPolicies2Layout.setVerticalGroup(
            pnlPolicies2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPolicies2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlPolicies2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPolicies2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addComponent(roundPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlPolicies.add(pnlPolicies2);

        pnlPolicies3.setBackground(new java.awt.Color(255, 255, 255));

        roundPanel8.setBackground(new java.awt.Color(255, 204, 153));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-trade-32.png"))); // NOI18N

        javax.swing.GroupLayout roundPanel8Layout = new javax.swing.GroupLayout(roundPanel8);
        roundPanel8.setLayout(roundPanel8Layout);
        roundPanel8Layout.setHorizontalGroup(
            roundPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundPanel8Layout.setVerticalGroup(
            roundPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Đổi trả dễ dàng");

        jLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("30 ngày không cần lý do");

        javax.swing.GroupLayout pnlPolicies3Layout = new javax.swing.GroupLayout(pnlPolicies3);
        pnlPolicies3.setLayout(pnlPolicies3Layout);
        pnlPolicies3Layout.setHorizontalGroup(
            pnlPolicies3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPolicies3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(roundPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPolicies3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlPolicies3Layout.setVerticalGroup(
            pnlPolicies3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPolicies3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlPolicies3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPolicies3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addComponent(roundPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlPolicies.add(pnlPolicies3);

        pnlPolicies5.setBackground(new java.awt.Color(255, 255, 255));

        roundPanel9.setBackground(new java.awt.Color(255, 204, 153));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-payment-32.png"))); // NOI18N

        javax.swing.GroupLayout roundPanel9Layout = new javax.swing.GroupLayout(roundPanel9);
        roundPanel9.setLayout(roundPanel9Layout);
        roundPanel9Layout.setHorizontalGroup(
            roundPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundPanel9Layout.setVerticalGroup(
            roundPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Thanh toán đa dạng");

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("COD & thanh toán online");

        javax.swing.GroupLayout pnlPolicies5Layout = new javax.swing.GroupLayout(pnlPolicies5);
        pnlPolicies5.setLayout(pnlPolicies5Layout);
        pnlPolicies5Layout.setHorizontalGroup(
            pnlPolicies5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPolicies5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(roundPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPolicies5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlPolicies5Layout.setVerticalGroup(
            pnlPolicies5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPolicies5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlPolicies5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPolicies5Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22))
                    .addComponent(roundPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlPolicies.add(pnlPolicies5);

        pnlShopContent.setBackground(new java.awt.Color(245, 247, 250));
        pnlShopContent.setOpaque(false);
        pnlShopContent.setLayout(new java.awt.BorderLayout());

        pnlGrid.setOpaque(false);
        pnlGrid.setLayout(new java.awt.GridLayout(0, 4, 70, 20));
        pnlGrid.add(productCard1);
        pnlGrid.add(productCard2);
        pnlGrid.add(productCard3);
        pnlGrid.add(productCard4);
        pnlGrid.add(productCard5);
        pnlGrid.add(productCard6);
        pnlGrid.add(productCard7);
        pnlGrid.add(productCard8);
        pnlGrid.add(productCard9);

        pnlShopContent.add(pnlGrid, java.awt.BorderLayout.NORTH);

        pnlCategory.setBackground(new java.awt.Color(255, 255, 255));
        pnlCategory.setPreferredSize(new java.awt.Dimension(0, 100));
        pnlCategory.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        all.setBackground(new java.awt.Color(255, 255, 255));
        all.setPreferredSize(new java.awt.Dimension(140, 80));

        AllCat.setBackground(new java.awt.Color(51, 102, 255));
        AllCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AllCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-opened-folder-36.png"))); // NOI18N
        AllCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllCatMouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Tất cả");

        javax.swing.GroupLayout allLayout = new javax.swing.GroupLayout(all);
        all.setLayout(allLayout);
        allLayout.setHorizontalGroup(
            allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AllCat, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap())
        );
        allLayout.setVerticalGroup(
            allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AllCat, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addContainerGap())
        );

        pnlCategory.add(all);

        Laptop.setBackground(new java.awt.Color(255, 255, 255));
        Laptop.setPreferredSize(new java.awt.Dimension(140, 80));

        LaptopCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LaptopCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-laptop-36.png"))); // NOI18N
        LaptopCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LaptopCatMouseClicked(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Laptop");

        javax.swing.GroupLayout LaptopLayout = new javax.swing.GroupLayout(Laptop);
        Laptop.setLayout(LaptopLayout);
        LaptopLayout.setHorizontalGroup(
            LaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LaptopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LaptopCat, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap())
        );
        LaptopLayout.setVerticalGroup(
            LaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LaptopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LaptopCat, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addContainerGap())
        );

        pnlCategory.add(Laptop);

        SmartPhone.setBackground(new java.awt.Color(255, 255, 255));
        SmartPhone.setPreferredSize(new java.awt.Dimension(140, 80));

        SmartPhoneCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SmartPhoneCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-phone-36_1.png"))); // NOI18N
        SmartPhoneCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SmartPhoneCatMouseClicked(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Điện thoại");

        javax.swing.GroupLayout SmartPhoneLayout = new javax.swing.GroupLayout(SmartPhone);
        SmartPhone.setLayout(SmartPhoneLayout);
        SmartPhoneLayout.setHorizontalGroup(
            SmartPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SmartPhoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SmartPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SmartPhoneCat, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap())
        );
        SmartPhoneLayout.setVerticalGroup(
            SmartPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SmartPhoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SmartPhoneCat, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addContainerGap())
        );

        pnlCategory.add(SmartPhone);

        HeadPhone.setBackground(new java.awt.Color(255, 255, 255));
        HeadPhone.setPreferredSize(new java.awt.Dimension(140, 80));

        HeadphoneCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HeadphoneCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-headphone-36.png"))); // NOI18N
        HeadphoneCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HeadphoneCatMouseClicked(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Tai nghe");

        javax.swing.GroupLayout HeadPhoneLayout = new javax.swing.GroupLayout(HeadPhone);
        HeadPhone.setLayout(HeadPhoneLayout);
        HeadPhoneLayout.setHorizontalGroup(
            HeadPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadPhoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeadPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HeadphoneCat, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap())
        );
        HeadPhoneLayout.setVerticalGroup(
            HeadPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadPhoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeadphoneCat, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addContainerGap())
        );

        pnlCategory.add(HeadPhone);

        Screen.setBackground(new java.awt.Color(255, 255, 255));
        Screen.setPreferredSize(new java.awt.Dimension(140, 80));

        ScreenCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScreenCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-screen-36.png"))); // NOI18N
        ScreenCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScreenCatMouseClicked(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Màn hình");

        javax.swing.GroupLayout ScreenLayout = new javax.swing.GroupLayout(Screen);
        Screen.setLayout(ScreenLayout);
        ScreenLayout.setHorizontalGroup(
            ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScreenCat, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap())
        );
        ScreenLayout.setVerticalGroup(
            ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScreenCat, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addContainerGap())
        );

        pnlCategory.add(Screen);

        SmartWatch.setBackground(new java.awt.Color(255, 255, 255));
        SmartWatch.setPreferredSize(new java.awt.Dimension(140, 80));

        SmartWatchCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SmartWatchCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-smart-watch-36.png"))); // NOI18N
        SmartWatchCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SmartWatchCatMouseClicked(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Đồng hồ thông minh");

        javax.swing.GroupLayout SmartWatchLayout = new javax.swing.GroupLayout(SmartWatch);
        SmartWatch.setLayout(SmartWatchLayout);
        SmartWatchLayout.setHorizontalGroup(
            SmartWatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SmartWatchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SmartWatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SmartWatchCat, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap())
        );
        SmartWatchLayout.setVerticalGroup(
            SmartWatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SmartWatchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SmartWatchCat, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel36)
                .addContainerGap())
        );

        pnlCategory.add(SmartWatch);

        GamingHand.setBackground(new java.awt.Color(255, 255, 255));
        GamingHand.setPreferredSize(new java.awt.Dimension(140, 80));

        GamingCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GamingCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-gaming-hand-36.png"))); // NOI18N
        GamingCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GamingCatMouseClicked(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Máy chơi game");

        javax.swing.GroupLayout GamingHandLayout = new javax.swing.GroupLayout(GamingHand);
        GamingHand.setLayout(GamingHandLayout);
        GamingHandLayout.setHorizontalGroup(
            GamingHandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamingHandLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GamingHandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GamingCat, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap())
        );
        GamingHandLayout.setVerticalGroup(
            GamingHandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamingHandLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GamingCat, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel38)
                .addContainerGap())
        );

        pnlCategory.add(GamingHand);

        PhuKien.setBackground(new java.awt.Color(255, 255, 255));
        PhuKien.setPreferredSize(new java.awt.Dimension(140, 80));

        PhuKienCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PhuKienCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/icons8-tech-36.png"))); // NOI18N
        PhuKienCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhuKienCatMouseClicked(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Phụ kiện");

        javax.swing.GroupLayout PhuKienLayout = new javax.swing.GroupLayout(PhuKien);
        PhuKien.setLayout(PhuKienLayout);
        PhuKienLayout.setHorizontalGroup(
            PhuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhuKienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PhuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PhuKienCat, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap())
        );
        PhuKienLayout.setVerticalGroup(
            PhuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhuKienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PhuKienCat, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel40)
                .addContainerGap())
        );

        pnlCategory.add(PhuKien);

        DanhMucText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DanhMucText.setText("Danh mục sản phẩm");

        javax.swing.GroupLayout pnlProductGridLayout = new javax.swing.GroupLayout(pnlProductGrid);
        pnlProductGrid.setLayout(pnlProductGridLayout);
        pnlProductGridLayout.setHorizontalGroup(
            pnlProductGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductGridLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(pnlProductGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlShopContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlProductGridLayout.createSequentialGroup()
                        .addComponent(DanhMucText)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlPolicies, javax.swing.GroupLayout.DEFAULT_SIZE, 1343, Short.MAX_VALUE)
                    .addComponent(pnlCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72))
        );
        pnlProductGridLayout.setVerticalGroup(
            pnlProductGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductGridLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pnlPolicies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(DanhMucText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlShopContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3718, 3718, 3718))
        );

        pnlWrapper.add(pnlProductGrid, java.awt.BorderLayout.CENTER);

        scrollPaneMain.setViewportView(pnlWrapper);

        getContentPane().add(scrollPaneMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void MyAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyAccountMouseClicked
        popMenuAvatar.show(MyAccount, 0, MyAccount.getHeight());
    }//GEN-LAST:event_MyAccountMouseClicked

    private void MyAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyAccountActionPerformed

    private void CartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CartActionPerformed

    private void menuAccountInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAccountInfActionPerformed

    }//GEN-LAST:event_menuAccountInfActionPerformed

    private void AllCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllCatMouseClicked
        loadDanhSachSanPham(0);
        setActiveCategoryLabel(AllCat);

    }//GEN-LAST:event_AllCatMouseClicked

    private void LaptopCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaptopCatMouseClicked
        loadDanhSachSanPham(1);
        setActiveCategoryLabel(LaptopCat);
    }//GEN-LAST:event_LaptopCatMouseClicked

    private void SmartPhoneCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SmartPhoneCatMouseClicked
        loadDanhSachSanPham(2);
        setActiveCategoryLabel(SmartPhoneCat);
    }//GEN-LAST:event_SmartPhoneCatMouseClicked

    private void HeadphoneCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeadphoneCatMouseClicked
        loadDanhSachSanPham(3);
        setActiveCategoryLabel(HeadphoneCat);
    }//GEN-LAST:event_HeadphoneCatMouseClicked

    private void ScreenCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScreenCatMouseClicked
        loadDanhSachSanPham(4);
        setActiveCategoryLabel(ScreenCat);
    }//GEN-LAST:event_ScreenCatMouseClicked

    private void SmartWatchCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SmartWatchCatMouseClicked
        loadDanhSachSanPham(5);
        setActiveCategoryLabel(SmartWatchCat);
    }//GEN-LAST:event_SmartWatchCatMouseClicked

    private void GamingCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GamingCatMouseClicked
        loadDanhSachSanPham(6);
        setActiveCategoryLabel(GamingCat);
    }//GEN-LAST:event_GamingCatMouseClicked

    private void PhuKienCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhuKienCatMouseClicked
        loadDanhSachSanPham(7);
        setActiveCategoryLabel(PhuKienCat);
    }//GEN-LAST:event_PhuKienCatMouseClicked

    private void BtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoutActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                null,
                "Bạn có chắc chắn muốn đăng xuất không?",
                "Xác nhận đăng xuất",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            TokenMonitorManager.stop();
            UserSession.clearSession();

            LoginForm login = new LoginForm();
            login.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_BtnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // 2. Khởi tạo FlatLaf (Giao diện phẳng hiện đại)
        try {
            com.formdev.flatlaf.FlatLightLaf.setup();
            javax.swing.UIManager.put("Table.alternateRowColor", new java.awt.Color(242, 242, 242));
        } catch (Exception ex) {
            System.err.println("Không thể khởi tạo FlatLaf, sẽ dùng giao diện mặc định");
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Đổi AdminForm thành LoginForm ở đây nhé
                new CustomerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AllCat;
    private Custom_Component.MyButton BtnLogout;
    private Custom_Component.MyButton Cart;
    private javax.swing.JLabel DanhMucText;
    private javax.swing.JLabel GamingCat;
    private Custom_Component.RoundPanel GamingHand;
    private Custom_Component.RoundPanel HeadPhone;
    private javax.swing.JLabel HeadphoneCat;
    private Custom_Component.RoundPanel Laptop;
    private javax.swing.JLabel LaptopCat;
    private Custom_Component.MyButton MyAccount;
    private Custom_Component.RoundPanel PhuKien;
    private javax.swing.JLabel PhuKienCat;
    private Custom_Component.RoundPanel Screen;
    private javax.swing.JLabel ScreenCat;
    private Custom_Component.RoundPanel SmartPhone;
    private javax.swing.JLabel SmartPhoneCat;
    private Custom_Component.RoundPanel SmartWatch;
    private javax.swing.JLabel SmartWatchCat;
    private Custom_Component.RoundPanel all;
    private Custom_Component.MyButton btnSearch;
    private Custom_Component.ImagePanel imagePanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel lblSoLuongGioHang;
    private javax.swing.JMenuItem menuAccountInf;
    private javax.swing.JMenuItem menuDonHang;
    private javax.swing.JMenuItem menuLoyaltyPoint;
    private Custom_Component.MyButton myButton4;
    private Custom_Component.MyButton myButton5;
    private javax.swing.JPanel pnlBanner;
    private Custom_Component.RoundPanel pnlCategory;
    private javax.swing.JPanel pnlGrid;
    private javax.swing.JPanel pnlHeader;
    private Custom_Component.RoundPanel pnlPolices1;
    private javax.swing.JPanel pnlPolicies;
    private Custom_Component.RoundPanel pnlPolicies2;
    private Custom_Component.RoundPanel pnlPolicies3;
    private Custom_Component.RoundPanel pnlPolicies5;
    private javax.swing.JPanel pnlProductGrid;
    private javax.swing.JPanel pnlShopContent;
    private javax.swing.JPanel pnlWrapper;
    private javax.swing.JPopupMenu popMenuAvatar;
    private View.panel.Customer.ProductCard productCard1;
    private View.panel.Customer.ProductCard productCard2;
    private View.panel.Customer.ProductCard productCard3;
    private View.panel.Customer.ProductCard productCard4;
    private View.panel.Customer.ProductCard productCard5;
    private View.panel.Customer.ProductCard productCard6;
    private View.panel.Customer.ProductCard productCard7;
    private View.panel.Customer.ProductCard productCard8;
    private View.panel.Customer.ProductCard productCard9;
    private Custom_Component.RoundPanel roundPanel1;
    private Custom_Component.RoundPanel roundPanel2;
    private Custom_Component.RoundPanel roundPanel6;
    private Custom_Component.RoundPanel roundPanel7;
    private Custom_Component.RoundPanel roundPanel8;
    private Custom_Component.RoundPanel roundPanel9;
    private javax.swing.JScrollPane scrollPaneMain;
    private Custom_Component.MyTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
