/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.AdminPortalPanel;

import Business.Sql.AccountSql;

import java.awt.Component;
import java.util.List;

import javax.swing.JButton;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HUY0406
 */
public class AccountPnl extends javax.swing.JPanel {

    /**
     * Creates new form AccountPnl
     */
    public AccountPnl() {
        initComponents();
        setupButtonColumn();
        setupComboboxColumn();
        loadAccountToTable();
    }

    private void loadAccountToTable() {
        DefaultTableModel model = (DefaultTableModel) tblAccount.getModel();
        model.setRowCount(0);

        AccountSql account = new AccountSql();
        // Lấy nguyên cái List chứa các cục Object (gồm ID và Name) về
        List<Object[]> accounts = account.getAllAccounts();

        // Lặp qua từng cục và đập lên bảng
        for (Object[] acc : accounts) {
            // acc[0] chính là Account_ID
            // acc[1] chính là Account_Name
            model.addRow(new Object[]{acc[0], acc[1], "--- Chọn Nhóm ---", "Lưu Quyền"});
        }
    }

    private void setupComboboxColumn() {
        javax.swing.JComboBox<String> cboGroup = new javax.swing.JComboBox<>();

        // Gọi hàm cũ của bro để lấy danh sách tên
        AccountSql account = new AccountSql();
        java.util.List<String> listName = account.getRoleGroupName();

        // Đổ vào Combobox
        for (String name : listName) {
            cboGroup.addItem(name);
        }

        // Nhét vào cột 2 của JTable
        javax.swing.table.TableColumn groupColumn = tblAccount.getColumnModel().getColumn(2);
        groupColumn.setCellEditor(new javax.swing.DefaultCellEditor(cboGroup));
    }

    private void setupButtonColumn() {
        javax.swing.table.TableColumn actionColumn = tblAccount.getColumnModel().getColumn(3);

        // 1. Hiển thị nút (Renderer)
        actionColumn.setCellRenderer((table, value, isSelected, hasFocus, row, column) -> {
            return new javax.swing.JButton("Lưu Quyền");
        });

        // 2. Xử lý khi bấm nút (Editor)
        actionColumn.setCellEditor(new javax.swing.DefaultCellEditor(new javax.swing.JCheckBox()) {
            private JButton button = new javax.swing.JButton("Lưu Quyền");
            private int currentRow;

            {
                button.addActionListener(e -> {
                    if (tblAccount.isEditing()) {
                        tblAccount.getCellEditor().stopCellEditing();
                    }

                    int accId = Integer.parseInt(tblAccount.getValueAt(currentRow, 0).toString());

                    String selectedGroupName = tblAccount.getValueAt(currentRow, 2).toString();

                    AccountSql accountSql = new AccountSql();

                    int groupId = accountSql.getGroupIdByName(selectedGroupName);

                    if (groupId != -1) {
                        System.out.println("Đang lưu Account " + accId + " vào Nhóm: " + selectedGroupName + " (ID: " + groupId + ")");

                        accountSql.assignGroupToAccount(accId, groupId);
                        JOptionPane.showMessageDialog(null, "Lưu thành công tài khoản vào nhóm " + selectedGroupName);
                    } else {
                        JOptionPane.showMessageDialog(null, "Lỗi: Không tìm thấy ID của nhóm " + selectedGroupName);
                    }
                });
            }

            @Override
            public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
                currentRow = row;
                return button;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRightWorkspace = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccount = new javax.swing.JTable();

        pnlRightWorkspace.setBackground(new java.awt.Color(240, 240, 240));
        pnlRightWorkspace.setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(241, 245, 249));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1000, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Account Management");

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Assign or update role permissions for user accounts");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2)))
                .addContainerGap(614, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlRightWorkspace.add(pnlHeader, java.awt.BorderLayout.NORTH);

        pnlContent.setBackground(new java.awt.Color(241, 245, 249));
        pnlContent.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        tblAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Account_ID", "Account_Name", "Account_Role_Group", "SAVE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAccount);

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );

        pnlRightWorkspace.add(pnlContent, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlRightWorkspace, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlRightWorkspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlRightWorkspace;
    private javax.swing.JTable tblAccount;
    // End of variables declaration//GEN-END:variables
}
