/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.AdminPortalPanel;

import Business.Sql.AccountSql;
import Common.Util.AppConstants;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author HUY0406
 */
public class RolePnl extends javax.swing.JPanel {

    /**
     * Creates new form RolePnl
     */
    private final String CURRENT_SCREEN = AppConstants.FUNC_ROLE_PERM;

    public RolePnl() {
        initComponents();
        changeItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRightWorkspace = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        cboFunction = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtRoleName = new Custom_Component.MyTextField();
        jLabel4 = new javax.swing.JLabel();
        chkThem = new javax.swing.JCheckBox();
        chkSua = new javax.swing.JCheckBox();
        chkXoa = new javax.swing.JCheckBox();
        chkTaiVe = new javax.swing.JCheckBox();
        chkXem = new javax.swing.JCheckBox();
        btnSubmit = new Custom_Component.MyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnDelete = new Custom_Component.MyButton();

        pnlRightWorkspace.setBackground(new java.awt.Color(240, 240, 240));
        pnlRightWorkspace.setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(241, 245, 249));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1000, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Role & Permission");

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Assign or update role permissions for user accounts");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2)))
                .addContainerGap(675, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlRightWorkspace.add(pnlHeader, java.awt.BorderLayout.NORTH);

        pnlContent.setBackground(new java.awt.Color(241, 245, 249));
        pnlContent.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        cboFunction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Account", "Product", "User" }));
        cboFunction.addActionListener(this::cboFunctionActionPerformed);

        jLabel3.setText("Chọn chức năng (Function_name)");

        jLabel4.setText("Nhập tên role");

        chkThem.setText("Thêm");
        chkThem.addActionListener(this::chkThemActionPerformed);

        chkSua.setText("Sửa");
        chkSua.addActionListener(this::chkSuaActionPerformed);

        chkXoa.setText("Xóa");
        chkXoa.addActionListener(this::chkXoaActionPerformed);

        chkTaiVe.setText("Tải về");
        chkTaiVe.addActionListener(this::chkTaiVeActionPerformed);

        chkXem.setText("Xem");
        chkXem.addActionListener(this::chkXemActionPerformed);

        btnSubmit.setBackground(new java.awt.Color(51, 51, 255));
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(this::btnSubmitActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnDelete.setBackground(new java.awt.Color(51, 51, 255));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cboFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRoleName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlContentLayout.createSequentialGroup()
                                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(pnlContentLayout.createSequentialGroup()
                                        .addComponent(chkThem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chkXoa)
                                        .addGap(26, 26, 26)
                                        .addComponent(chkSua)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkXem)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkTaiVe))
                                    .addGroup(pnlContentLayout.createSequentialGroup()
                                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRoleName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkThem)
                            .addComponent(chkXoa)
                            .addComponent(chkSua)
                            .addComponent(chkXem)
                            .addComponent(chkTaiVe))
                        .addGap(18, 18, 18)
                        .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlContentLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlRightWorkspace.add(pnlContent, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 991, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlRightWorkspace, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(pnlRightWorkspace, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void changeItem() {
        AccountSql account = new AccountSql();
        List<String> listName = account.getFunctionName();

        cboFunction.removeAllItems();
        for (String name : listName) {
            cboFunction.addItem(name);
        }
    }

    private void chkThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkThemActionPerformed

    private void chkSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSuaActionPerformed

    private void chkXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkXoaActionPerformed

    private void chkTaiVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTaiVeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTaiVeActionPerformed

    private void chkXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkXemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkXemActionPerformed

    private void cboFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFunctionActionPerformed

    }//GEN-LAST:event_cboFunctionActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        String role = txtRoleName.getText();
        String func = cboFunction.getSelectedItem().toString();

        int a = chkThem.isSelected() ? 1 : 0;
        int e = chkSua.isSelected() ? 1 : 0;
        int d = chkXoa.isSelected() ? 1 : 0;
        int v = chkXem.isSelected() ? 1 : 0;
        int dl = chkTaiVe.isSelected() ? 1 : 0;

        AccountSql account = new AccountSql();
        if (account.savePermission(role, func, a, e, d, v, dl)) {
            JOptionPane.showMessageDialog(this, "Lưu thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Lưu thất bại!");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String role = txtRoleName.getText();
        String func = cboFunction.getSelectedItem().toString();

        int confirm = JOptionPane.showConfirmDialog(this, "Chắc chắn muốn xóa quyền của " + role + " không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        AccountSql account = new AccountSql();
        if (confirm == JOptionPane.YES_OPTION) {
            if (account.deletePermission(role, func)) {
                JOptionPane.showMessageDialog(this, "Đã xóa xong!");
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy để xóa!");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom_Component.MyButton btnDelete;
    private Custom_Component.MyButton btnSubmit;
    private javax.swing.JComboBox<String> cboFunction;
    private javax.swing.JCheckBox chkSua;
    private javax.swing.JCheckBox chkTaiVe;
    private javax.swing.JCheckBox chkThem;
    private javax.swing.JCheckBox chkXem;
    private javax.swing.JCheckBox chkXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlRightWorkspace;
    private Custom_Component.MyTextField txtRoleName;
    // End of variables declaration//GEN-END:variables
}
