/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.auth;

import Controller.LoginController;
import Service.AuthService;
import Util.HashUtil;
import Util.TokenMonitorManager;
import Model.AccountModel;
import View.admin.AdminForm;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author HUY0406
 */
public class LoginForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        LoginController controller = new LoginController(this);
        this.setSize(1100, 650);
        this.setResizable(true);
        this.setLocationRelativeTo(null);
        // TẠO MÀU BACKGROUND
        java.awt.Container oldContentPane = this.getContentPane();
        if (oldContentPane instanceof javax.swing.JPanel jPanel) {
            jPanel.setOpaque(false);
        }

        javax.swing.JPanel backgroundLayer = new javax.swing.JPanel(new java.awt.BorderLayout()) {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;
                // Cam đào (Top) xuống Hồng nhạt (Bottom)
                java.awt.GradientPaint gp = new java.awt.GradientPaint(
                        0, 0, new java.awt.Color(255, 218, 185),
                        0, getHeight(), new java.awt.Color(255, 182, 193)
                );
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        backgroundLayer.add(oldContentPane);
        this.setContentPane(backgroundLayer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        roundPanel1 = new Custom_Component.RoundPanel();
        imagePanel2 = new Custom_Component.ImagePanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passText = new javax.swing.JLabel();
        userNameField = new Custom_Component.MyTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordField = new Custom_Component.MyPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        forgetPassText = new javax.swing.JLabel();
        btnSignIn = new Custom_Component.MyButton();
        signUpText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel1.setPreferredSize(new java.awt.Dimension(1000, 580));
        roundPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagePanel2.setImage(new javax.swing.ImageIcon(getClass().getResource("/Resource/backgroundLogin3.png"))); // NOI18N
        imagePanel2.setPreferredSize(new java.awt.Dimension(460, 540));

        javax.swing.GroupLayout imagePanel2Layout = new javax.swing.GroupLayout(imagePanel2);
        imagePanel2.setLayout(imagePanel2Layout);
        imagePanel2Layout.setHorizontalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        imagePanel2Layout.setVerticalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        roundPanel1.add(imagePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("\nĐĂNG NHẬP");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 50));
        roundPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vui lòng nhập thông tin tài khoản của bạn");
        roundPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 300, 30));

        passText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passText.setText("Mật khẩu");
        roundPanel1.add(passText, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 265, 310, 30));

        userNameField.setPreferredSize(new java.awt.Dimension(400, 45));
        roundPanel1.add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Tên đăng nhập");
        roundPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 310, 30));

        passwordField.setPreferredSize(new java.awt.Dimension(400, 45));
        passwordField.addActionListener(this::passwordFieldActionPerformed);
        roundPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 295, -1, -1));

        jCheckBox1.setText("Ghi nhớ đăng nhập");
        roundPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 355, -1, -1));

        forgetPassText.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        forgetPassText.setForeground(new java.awt.Color(0, 51, 255));
        forgetPassText.setText("Quên mật khẩu?");
        roundPanel1.add(forgetPassText, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 355, 90, -1));

        btnSignIn.setBackground(new java.awt.Color(255, 107, 53));
        btnSignIn.setForeground(new java.awt.Color(255, 255, 255));
        btnSignIn.setColorClick(new java.awt.Color(227, 85, 32));
        btnSignIn.setColorHover(new java.awt.Color(255, 133, 86));
        btnSignIn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSignIn.setLabel("ĐĂNG NHẬP");
        btnSignIn.setPreferredSize(new java.awt.Dimension(400, 45));
        btnSignIn.addActionListener(this::btnSignInActionPerformed);
        roundPanel1.add(btnSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 400, -1));

        signUpText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signUpText.setText("<html>Chưa có tài khoản? <font color='#001CBA'><b>Đăng ký ngay</b></font></html>");
        signUpText.setPreferredSize(new java.awt.Dimension(400, 25));
        signUpText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpTextMouseClicked(evt);
            }
        });
        roundPanel1.add(signUpText, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 475, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(roundPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed

        LoginController controller = new LoginController(this);
        controller.handleLogin();
    }//GEN-LAST:event_btnSignInActionPerformed

    private void signUpTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpTextMouseClicked
        RegisterForm register = new RegisterForm();
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signUpTextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom_Component.MyButton btnSignIn;
    private javax.swing.JLabel forgetPassText;
    private Custom_Component.ImagePanel imagePanel2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel passText;
    public Custom_Component.MyPasswordField passwordField;
    private Custom_Component.RoundPanel roundPanel1;
    private javax.swing.JLabel signUpText;
    public Custom_Component.MyTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
